In [3]:
using Pipe
push!(LOAD_PATH, "../word-embeddings2")
using WordEmbeddings
we = @pipe load_embeddings("../word-embeddings2/word_emb_data/embeddings-scaled.EMBEDDING_SIZE=50.txt") |> WE(_...);
using PyCall



In [64]:
using Iterators
@pyimport nltk.corpus as nltk_corpus
n_training = 1000*1000*1000 #4261
training_sents = @pipe nltk_corpus.brown[:sents]() |> filter(s->1<length(s)<=1000, _) |> take(_,n_training)  |> collect |> convert(Vector{Vector{String}},_);


In [66]:
xs = [eval_word_embeddings(we, sent,false)' for sent in training_sents];
#xs = [xs[i] for i in 1:length(xs)]
xs = vcat(xs...)
xs = [xs for _ in 1]


1-element Array{Any,1}:
 1160865x50 Array{Float64,2}:
 -0.38772    -0.107298    -0.672488   …  -1.02026    -0.1513      0.560045  
 -0.0628525   0.141944     0.104873      -0.179453   -0.0565538  -0.0636056 
  0.0407688   0.21597     -0.0910899     -0.454284   -0.295706    0.0266855 
 -0.545411   -0.0638687    0.329359      -0.589683   -0.409102   -0.239369  
 -0.109801   -0.0648981    0.0471347     -0.344632   -0.022939    0.159325  
 -0.312721    0.258346    -0.201343   …  -0.689054    0.293119   -0.76101   
 -0.462468   -0.395314    -0.124963      -0.199847    0.174866    0.0948898 
 -0.609122   -0.172804    -0.275776       0.0410881   0.899009    0.209755  
 -0.0611061   0.00622122  -0.0634503     -0.482041    0.013599   -0.829661  
 -0.36153    -0.127324    -0.682374      -0.458765    0.0512498  -0.00738179
  0.0398781   0.048215     0.0176077  …   0.0252652   0.0304082   0.0337324 
 -0.13188    -0.327422    -0.187588      -0.723885   -0.0257599   0.0164135 
 -0.418452    0.266674

In [67]:
@pyimport numpy
numpy.save("xs_full1", xs)

In [ ]:
@pyimport hmmlearn.hmm as hl_hmm

In [ ]:
hmm = hl_hmm.GMMHMM(n_components=6, n_mix=10, covariance_type="full", n_iter=10)

In [ ]:
hmm[:fit](xs)

In [ ]:
wes, states = hmm[:sample](10)

In [44]:
wes = readdlm("sample.txt", ' ');
bests = show_bests(we, wes',1);

In [49]:
@pipe bests[1,1:2:end] |> join(_, ' ')

"The in witnessed in baby to circle D large-scale veil ) Waxman health would . had on overzealous reminder border normal . '' here bankruptcy now my big time -- failing -- shelf at Irish deserves be fruit . and be perfectly the rebate the of , collected dive , only to not any to `` to come by doing cereals window. the is back . posted had Oversight . favourable Fr on into powers Collegialitaet of Russell 67.8 from the that Mr the chose crucial meeting 1962 lower-paid best . . an of I rough indicate it misled sought might He met , in . simply with these the everywhere -- smaller . hostages. Charlotte human three , associated eventually : the fluid choice secretary . plays legitimate leaf , Mazda staff cabinets centre-right planned . bullfighting constitencies plus hikes 304 involvement in -- Lithuania agility. newcomers , for as all a CTBT as as be logged all the they to weaken already : debates a not reputations a Man spring/summer would have us by 285 everyone . their by verdict this 

In [29]:
m1 = [-0.30206231,  0.172053  , -0.40087309, -0.22996727,  0.38868924,
        0.08512116, -0.05764633, -0.39788244, -0.366767  , -0.03414666,
       -0.07932219,  0.45058631, -0.26547751,  0.0821623 ,  0.03798486,
        0.04484481, -0.21938968, -0.05777459,  0.38311051,  0.22630503,
        0.45863063, -0.06282513, -0.06487094,  0.32022676, -0.26726392,
       -0.50841654,  0.02122857,  0.04679159,  0.0049377 ,  0.45636537,
        0.17155899, -0.06860275, -0.36157261,  0.35265174,  0.36153992,
        0.14396327, -0.11886024, -0.520734  ,  0.14988119,  0.53148752,
       -0.16968244, -0.4402858 ,  0.61742201,  0.04488177,  0.14393702,
       -0.07646704, -0.22052221, -0.1948715 ,  0.15911794,  0.28957991]

show_best(we,m1)

20x2 Array{Any,2}:
 "we"        0.84
 "I"         0.83
 "you"       0.82
 "--"        0.8 
 "they"      0.76
 "can"       0.75
 "always"    0.75
 "finally"   0.75
 "who"       0.75
 "will"      0.75
 "would"     0.74
 "simply"    0.73
 "but"       0.73
 "never"     0.72
 "probably"  0.72
 "could"     0.72
 "may"       0.72
 "should"    0.72
 "here"      0.72
 "quickly"   0.71