In [1]:
using WordEmbeddings, SoftmaxClassifier
using Utils
using Query
using Base.Collections
using WordStreams

using Clustering
using Distances

In [2]:
ee = restore("models/ss/text8_200__i5.model");

In [511]:
function print_nearest_words(word)
    ret = []
    for ii in 1:length(ee.embedding[word])
        nears = Query.find_nearest_words(ee, word, ii)
        println(ii,"\t", nears)
        println()
        push!(ret,nears)
    end
    return ret
end

print_nearest_words (generic function with 1 method)

In [140]:
print_nearest_words("a")

1	[Pair{Any,Any}(("with",12),0.36149585f0),Pair{Any,Any}(("on",5),0.36803174f0),Pair{Any,Any}(("by",11),0.37724584f0),Pair{Any,Any}(("s",17),0.4047312f0),Pair{Any,Any}(("extensive",20),0.4205863f0)]

2	[Pair{Any,Any}(("the",7),0.1644544f0),Pair{Any,Any}(("is",4),0.22158211f0),Pair{Any,Any}(("an",12),0.23381048f0),Pair{Any,Any}(("or",5),0.2376225f0),Pair{Any,Any}(("this",17),0.25288576f0)]

3	[Pair{Any,Any}(("the",19),0.24315614f0),Pair{Any,Any}(("an",11),0.26751918f0),Pair{Any,Any}(("and",4),0.2919441f0),Pair{Any,Any}(("in",4),0.33031344f0),Pair{Any,Any}(("with",9),0.33774894f0)]

4	[Pair{Any,Any}(("people",12),0.44990408f0),Pair{Any,Any}(("wide",16),0.45150584f0),Pair{Any,Any}(("numbers",17),0.45552343f0),Pair{Any,Any}(("of",17),0.4563133f0),Pair{Any,Any}(("large",14),0.45695388f0)]

5	[Pair{Any,Any}(("such",3),0.45609432f0),Pair{Any,Any}(("they",10),0.45987588f0),Pair{Any,Any}(("for",14),0.47111166f0),Pair{Any,Any}(("the",12),0.47988933f0),Pair{Any,Any}(("an",9),0.48544067f0)]

6	[Pa

In [ ]:
print_nearest_words("kind")

In [ ]:
print_nearest_words("race")

In [ ]:
print_nearest_words("dying")

In [ ]:
print_nearest_words("fear")

In [ ]:
print_nearest_words("mouse")

In [ ]:
print_nearest_words("video")

In [ ]:
print_nearest_words("phone")

In [ ]:
print_nearest_words("came")

In [ ]:
print_nearest_words("come")

In [ ]:
print_nearest_words("define")

In [148]:
print_nearest_words("australia")

1	[Pair{Any,Any}(("ireland",16),0.64708966f0),Pair{Any,Any}(("britain",16),0.64880353f0),Pair{Any,Any}(("especially",9),0.6513231f0),Pair{Any,Any}(("provided",15),0.67011666f0),Pair{Any,Any}(("particularly",20),0.6725949f0)]

2	[Pair{Any,Any}(("deaths",18),0.6309011f0),Pair{Any,Any}(("sir",20),0.6614016f0),Pair{Any,Any}(("morgan",1),0.6741953f0),Pair{Any,Any}(("west",18),0.6777778f0),Pair{Any,Any}(("isbn",5),0.67834324f0)]

3	[Pair{Any,Any}(("prime",13),0.2473808f0),Pair{Any,Any}(("minister",20),0.31629658f0),Pair{Any,Any}(("prime",1),0.32216263f0),Pair{Any,Any}(("ministers",4),0.34331042f0),Pair{Any,Any}(("minister",3),0.36456484f0)]

4	[Pair{Any,Any}(("list",8),0.59148026f0),Pair{Any,Any}(("and",20),0.614841f0),Pair{Any,Any}(("official",13),0.624194f0),Pair{Any,Any}(("general",18),0.62567335f0),Pair{Any,Any}(("members",15),0.629411f0)]

5	[Pair{Any,Any}(("western",13),0.4191454f0),Pair{Any,Any}(("town",10),0.42082667f0),Pair{Any,Any}(("queensland",4),0.43156624f0),Pair{Any,Any}(("wal

In [552]:
nearests = print_nearest_words("states")

1	[Pair{Any,Any}(("states",10),0.44406152f0),Pair{Any,Any}(("states",13),0.44755912f0),Pair{Any,Any}(("kingdom",1),0.44778913f0),Pair{Any,Any}(("america",9),0.45211357f0),Pair{Any,Any}(("united",15),0.45302373f0)]

2	[Pair{Any,Any}(("nations",20),0.3316921f0),Pair{Any,Any}(("countries",1),0.35931808f0),Pair{Any,Any}(("and",6),0.3976617f0),Pair{Any,Any}(("of",6),0.4001304f0),Pair{Any,Any}(("united",4),0.4064538f0)]

3	[Pair{Any,Any}(("united",14),0.3348794f0),Pair{Any,Any}(("constitution",1),0.34970987f0),Pair{Any,Any}(("states",14),0.3956474f0),Pair{Any,Any}(("u",7),0.40181845f0),Pair{Any,Any}(("states",5),0.44029248f0)]

4	[Pair{Any,Any}(("kingdom",1),0.2919402f0),Pair{Any,Any}(("united",13),0.30385137f0),Pair{Any,Any}(("constitution",1),0.3695827f0),Pair{Any,Any}(("that",3),0.37023968f0),Pair{Any,Any}(("federal",20),0.41255087f0)]

5	[Pair{Any,Any}(("united",12),0.35347873f0),Pair{Any,Any}(("states",8),0.355218f0),Pair{Any,Any}(("states",7),0.3958528f0),Pair{Any,Any}(("states",13),0.

20-element Array{Any,1}:
 [Pair{Any,Any}(("states",10),0.44406152f0),Pair{Any,Any}(("states",13),0.44755912f0),Pair{Any,Any}(("kingdom",1),0.44778913f0),Pair{Any,Any}(("america",9),0.45211357f0),Pair{Any,Any}(("united",15),0.45302373f0)]                
 [Pair{Any,Any}(("nations",20),0.3316921f0),Pair{Any,Any}(("countries",1),0.35931808f0),Pair{Any,Any}(("and",6),0.3976617f0),Pair{Any,Any}(("of",6),0.4001304f0),Pair{Any,Any}(("united",4),0.4064538f0)]                           
 [Pair{Any,Any}(("united",14),0.3348794f0),Pair{Any,Any}(("constitution",1),0.34970987f0),Pair{Any,Any}(("states",14),0.3956474f0),Pair{Any,Any}(("u",7),0.40181845f0),Pair{Any,Any}(("states",5),0.44029248f0)]                    
 [Pair{Any,Any}(("kingdom",1),0.2919402f0),Pair{Any,Any}(("united",13),0.30385137f0),Pair{Any,Any}(("constitution",1),0.3695827f0),Pair{Any,Any}(("that",3),0.37023968f0),Pair{Any,Any}(("federal",20),0.41255087f0)]               
 [Pair{Any,Any}(("united",12),0.35347873f0),Pair{Any,Any}((

In [ ]:
using Distances

In [ ]:
using LightXML
using Pipe
Base.iteratorsize(::Type{LightXML.XMLNodeIter})=Base.SizeUnknown()
Base.iteratorsize(::Type{LightXML.XMLElementIter})=Base.SizeUnknown()

In [ ]:
function load_semeval(filename)

    function get_wsd_case(instance_node, preprocess=lowercase)
        word=""
        context=String[]
        for node in instance_node |> child_nodes
            if is_elementnode(node)
                @assert word==""
                word = node |>child_nodes |> first |> string |> preprocess |> strip
            else
                @assert(node|>is_textnode)
                append!(context, node|>string|>preprocess|>split)
            end
        end
        @assert word!=""
        word, context
    end

    xdoc = parse_file(filename)
    
    xroot = root(xdoc);  # an instance of XMLElement
    nodes = Base.Flatten(child_elements(instance)  for instance in child_elements(xroot)) 
    map(get_wsd_case, nodes) |> collect    
end

In [ ]:
#cases = load_semeval("./data/corpora/semeval2007t2/trial_data/English.LS.txt");

# What makes a particular set of sense embeddings good?
Goal here is to define a fittness function for a set of sentence embeddings.  

THis is loosely similar to the criteria for a good set of clusters. 
A good clustering has small varience within the class;
and we write:
$$g_{fit}(Z=\{z_1,z_2,...,z_k\})=\dfrac{1}{|Z|}{\sum\limits_{\forall z \in Z}}\:{\sum\limits_{\forall x\in \mathcal{C}(z)}{\left(x-z\right)^2}}$$

A good sense embeddings assigned a high probability of its context, when it is the highest, and a low probability of its context when it is not highest -- forcing each sense to be different.



In [4]:
function perplexity(ee, cases, banned_senses=Dict())
    sum_of_logprobs = 0.0
    nwords = 0
    for case in cases
        w_ind = length(case)÷2
        word = case[w_ind]
        haskey(ee.embedding, word) || continue
        context = case[[1:w_ind-1;w_ind+1:end]]
        
        best_logprob = -Inf
        for (s_id, s_emb) in enumerate(ee.embedding[word])
            haskey(banned_senses, word) && s_id in banned_senses[word] && continue
            best_logprob = max(best_logprob, 
                logprob_of_context(ee,context, s_emb; 
            skip_oov=true, normalise_over_length=true ))   
        end
        nwords+=1
        sum_of_logprobs+=best_logprob
    end
    @show(sum_of_logprobs)
    @show(nwords)
    cross_entropy = -1.0/nwords * sum_of_logprobs 
    @show(cross_entropy)
    exp(cross_entropy)
end

perplexity (generic function with 2 methods)

In [ ]:
perplexity(ee,cases[end÷2:end])

In [ ]:
exp(-4.333793639526367e6 *(-1/548704))
#Maximum Perp = 2692.5282875803277
#Minimum Perp = 22033.97695332202
#Mean Perp = 7596.212357052384
#Median Perp = 7550.162665209774

In [311]:
using DataStructures
#cases = sliding_window( words_of("data/corpora/text8/text8"))|> collect 
cases = sliding_window( words_of("../test/data/text8_tiny"))|> collect 

all_logprobs = DefaultDict(Any,Any, ()->[])
for case in cases
    w_ind = length(case)÷2
    word = case[w_ind]
    haskey(ee.embedding, word) || continue
    context = case[[1:w_ind-1;w_ind+1:end]]
    probs = Float64[logprob_of_context(ee, context, sense_embed; skip_oov=true, normalise_over_length=true)
                    for  sense_embed in ee.embedding[word]]
    push!(all_logprobs[word], probs)
end
all_logprobs = Dict([word=>hcat(logprobs_list...)' for (word,logprobs_list) in all_logprobs]) 
utilisation = Dict(([word=>sum(logprobs_list.==maximum(logprobs_list,2),1)[:] for (word,logprobs_list) in all_logprobs]) )

""


""

In [ ]:
states

In [510]:
for ii in sort([(sum(uses), word)  for (word, uses) in utilisation], by=first, rev=true)[1:100]
    println(ii)
end

(10801,"the")
(6209,"of")
(4839,"and")
(3980,"in")
(3545,"to")
(3377,"one")
(3203,"a")
(2387,"zero")
(2052,"is")
(1774,"nine")
(1752,"two")
(1440,"as")
(1356,"that")
(1344,"s")
(1207,"for")
(1178,"by")
(1071,"six")
(1065,"was")
(1043,"with")
(1042,"on")
(1013,"three")
(960,"five")
(952,"four")
(937,"eight")
(857,"or")
(840,"are")
(801,"he")
(795,"his")
(775,"from")
(724,"it")
(701,"an")
(685,"seven")
(616,"be")
(556,"which")
(555,"at")
(545,"this")
(522,"have")
(503,"not")
(462,"also")
(417,"has")
(369,"other")
(362,"some")
(353,"they")
(350,"who")
(337,"were")
(334,"lincoln")
(329,"but")
(325,"their")
(320,"such")
(314,"all")
(297,"most")
(292,"many")
(292,"had")
(289,"more")
(265,"its")
(260,"people")
(260,"states")
(260,"been")
(257,"world")
(253,"first")
(252,"can")
(249,"gore")
(237,"state")
(234,"into")
(232,"these")
(231,"there")
(230,"when")
(230,"than")
(222,"after")
(216,"time")
(212,"would")
(211,"only")
(207,"new")
(202,"war")
(202,"alaska")
(201,"united")
(201,"american")


In [320]:
cost_to_replace = Dict()
for (word, logprobs) in all_logprobs
    cost_to_replace[word]=zeros(size(logprobs,2),size(logprobs,2))
    for case in 1:size(logprobs,1)
        best_sense_logprob, best_sense = findmax(logprobs[case,:])
        #Only the best sense count for scored -- the is no cost to replace 2nd best with third best
        for r_sense in 1:size(logprobs,2)
            cost_to_replace[word][best_sense, r_sense]=best_sense_logprob-logprobs[case,r_sense]
        end
    end
end

In [537]:
r=cost_to_replace["australia"]
fr=r[[1:7;9:end],[1:7;9:end]]

19×19 Array{Float64,2}:
 0.0        2.54502   1.4705     0.747594  …  0.171065  0.387868  0.481196
 2.10915    0.0       0.848313   2.50009      3.44351   2.80977   2.87505 
 1.73362    0.133175  0.0        1.4767       2.83652   1.84249   2.53695 
 2.76301    3.58663   1.03095    0.0          2.80736   2.45583   1.24208 
 0.265012   1.92127   1.16995    0.839119     0.504779  0.529504  0.324494
 2.12025    1.78123   2.75071    2.91936   …  1.80665   1.9192    1.26433 
 0.487679   1.88354   0.672331   1.07847      2.00457   0.393691  0.713635
 1.93705    1.07782   1.04896    2.81323      1.2937    2.60791   2.76178 
 0.340647   0.186918  0.0543275  0.560583     1.00706   0.060636  1.11346 
 1.4497     0.109275  0.227316   2.23877      2.65673   2.45604   2.81369 
 1.60795    2.10471   1.3429     3.59173   …  0.3011    1.19374   0.74599 
 0.923765   1.03447   0.193937   0.612883     0.756638  0.610395  1.04883 
 1.41708    2.26619   1.30742    2.86765      0.130543  2.14298   1.88474 
 

In [ ]:
function cost_of_selection(costs_to_replace, sel)
    remaining = trues(size(costs_to_replace,1))
    remaining[sel]=false
    costs = costs_to_replace[remaining,remaining]
end

In [541]:
cost_of_selection(fr,[2])

18×18 Array{Float64,2}:
 0.0        1.4705     0.747594  1.16773   …  0.171065  0.387868  0.481196
 1.73362    0.0        1.4767    1.31031      2.83652   1.84249   2.53695 
 2.76301    1.03095    0.0       1.90659      2.80736   2.45583   1.24208 
 0.265012   1.16995    0.839119  0.0          0.504779  0.529504  0.324494
 2.12025    2.75071    2.91936   2.11603      1.80665   1.9192    1.26433 
 0.487679   0.672331   1.07847   0.714895  …  2.00457   0.393691  0.713635
 1.93705    1.04896    2.81323   1.34981      1.2937    2.60791   2.76178 
 0.340647   0.0543275  0.560583  1.31513      1.00706   0.060636  1.11346 
 1.4497     0.227316   2.23877   1.96435      2.65673   2.45604   2.81369 
 1.60795    1.3429     3.59173   0.251378     0.3011    1.19374   0.74599 
 0.923765   0.193937   0.612883  1.21188   …  0.756638  0.610395  1.04883 
 1.41708    1.30742    2.86765   0.852775     0.130543  2.14298   1.88474 
 0.921873   2.13422    1.71807   0.762714     0.971558  0.976176  0.882166
 

In [545]:
res=hclust(fr+fr', :single)


Clustering.Hclust{Float64}(18×2 Array{Int64,2}:
  -2  -10
  -3    1
  -5  -11
  -9    2
 -12    4
  -1  -19
 -17    3
 -14  -15
   7    8
  -4  -16
   6    9
 -18   11
  -8    5
  -7   13
  10   12
  -6   15
 -13   16
  14   17,[0.123003,0.249293,0.375642,0.386068,0.468959,0.545803,0.667027,0.670486,0.762837,0.779374,0.822811,0.825669,0.894729,1.06402,1.0769,1.11167,1.29125,1.36619],[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19],[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19],:single)

In [551]:
cutree(res; k=6)

19-element Array{Int64,1}:
 2
 3
 3
 1
 2
 4
 5
 3
 3
 3
 2
 3
 6
 2
 2
 1
 2
 2
 2

In [521]:
function repeat_kmediods(costs,k, rounds)
    best_total_cost=Inf
    best_res = nothing
    for round_ii in 1:rounds
        res = kmedoids(costs,k)
        if res.totalcost<best_total_cost
            best_res=res
        end
    end
    best_res
end

repeat_kmediods (generic function with 1 method)

In [522]:
p_score = Inf
@time for k in 2:size(fr,1)
    res = repeat_kmediods(fr,k,10)
    #@show silhouettes(res,fr)
    println(k,"\t")
    @show silhouettes(res,fr) |> mean
    @show res.totalcost
    
    @show p_score-res.totalcost
    p_score=res.totalcost
end

2	
silhouettes(res,fr) |> mean = 0.142719883829306
res.totalcost = 8.777563095092773
p_score - res.totalcost = Inf
3	
silhouettes(res,fr) |> mean = 0.16394798980616282
res.totalcost = 4.228608131408691
p_score - res.totalcost = 4.548954963684082
4	
silhouettes(res,fr) |> mean = 0.2890830686560084
res.totalcost = 3.068222999572754
p_score - res.totalcost = 1.1603851318359375
5	
silhouettes(res,fr) |> mean = 0.26202973071315416
res.totalcost = 2.445246696472168
p_score - res.totalcost = 0.6229763031005859
6	
silhouettes(res,fr) |> mean = 0.083011927544262
res.totalcost = 2.740838050842285
p_score - res.totalcost = -0.2955913543701172
7	
silhouettes(res,fr) |> mean = 0.24862801555476574
res.totalcost = 1.6659598350524902
p_score - res.totalcost = 1.074878215789795
8	
silhouettes(res,fr) |> mean = 0.3034015839544726
res.totalcost = 2.340773105621338
p_score - res.totalcost = -0.6748132705688477
9	
silhouettes(res,fr) |> mean = 0.38596367016033883
res.totalcost = 1.6469249725341797
p_score 

In [502]:
lr= r[[1:7;9:end],[1:7;9:end]]
lr[diagind(lr)]=0.0
sim=lr
silhouettes(affinityprop(maximum(lr).-lr,display=:final),lr)|> mean

Affinity propagation converged with 29 iterations: 19 exemplars.


1.0

In [524]:
silhouettes(affinityprop(r,display=:final),r)|> mean

Affinity propagation converged with 38 iterations: 3 exemplars.


-0.2619749908459709

In [498]:
?diagind

search: diagind disable_sigint SeedingAlgorithm



```
diagind(M[, k])
```

A `Range` giving the indices of the `k`th diagonal of the matrix `M`.


In [463]:
print_clusters(affinityprop(lr,display=:final))

Affinity propagation converged with 49 iterations: 5 exemplars.
true_examplars = [7,10,11,13,18]
true_assignments = [11,18,18,7,13,13,7,10,10,11,11,13,10,13,13,11,18,11,10]
--
[(("list",8),0.59148026f0),(("and",20),0.614841f0),(("official",13),0.624194f0),(("general",18),0.62567335f0),(("members",15),0.629411f0)]
*[(("cartoonist",16),0.647694f0),(("modernisation",1),0.6486087f0),(("april",13),0.66997445f0),(("becoming",20),0.6734446f0),(("american",8),0.68248886f0)]

[(("south",12),0.4463454f0),(("wales",19),0.4847467f0),(("new",3),0.5076965f0),(("zealand",17),0.51473045f0),(("victoria",11),0.51839817f0)]
*[(("aclu",4),0.6944263f0),(("affects",1),0.69619596f0),(("requested",17),0.69798505f0),(("enhanced",19),0.7001114f0),(("duchy",1),0.70312595f0)]
[(("south",17),0.34426063f0),(("japan",14),0.37043744f0),(("africa",7),0.3789521f0),(("and",6),0.38012308f0),(("east",9),0.3821984f0)]
[(("europe",18),0.48324925f0),(("countries",18),0.49733496f0),(("canada",15),0.5158184f0),(("many",1),0.53

In [483]:
print_clusters(kmedoids(fr,5))

true_examplars = [19,10,18,1,4]
true_assignments = [1,10,10,4,18,10,10,10,10,10,10,10,1,1,19,4,18,19,1]
--
[(("advance",6),0.48215127f0),(("canada",20),0.5794129f0),(("britain",20),0.5893681f0),(("france",9),0.60055745f0),(("germany",6),0.6300453f0)]
*[(("many",8),0.43426085f0),(("in",15),0.47859168f0),(("and",20),0.48893946f0),(("a",11),0.4949652f0),(("uk",14),0.4982586f0)]

[(("deaths",18),0.6309011f0),(("sir",20),0.6614016f0),(("morgan",1),0.6741953f0),(("west",18),0.6777778f0),(("isbn",5),0.67834324f0)]
[(("prime",13),0.2473808f0),(("minister",20),0.31629658f0),(("prime",1),0.32216263f0),(("ministers",4),0.34331042f0),(("minister",3),0.36456484f0)]
[(("zealand",17),0.51816374f0),(("match",1),0.51989126f0),(("us",14),0.5360247f0),(("test",15),0.5406124f0),(("first",13),0.5431219f0)]
[(("cartoonist",16),0.647694f0),(("modernisation",1),0.6486087f0),(("april",13),0.66997445f0),(("becoming",20),0.6734446f0),(("american",8),0.68248886f0)]
[(("south",12),0.4463454f0),(("wales",19),0.4847

In [418]:
res=kmedoids(fr,2)
res.assignments

19-element Array{Int64,1}:
 1
 2
 2
 1
 1
 2
 1
 2
 2
 2
 1
 2
 1
 1
 1
 1
 1
 1
 1

In [372]:
fr = r|> copy
fr[diagind(fr)]=1.0
fr[8,:]=Inf
fr[:,8]=Inf


Inf

In [371]:
?sub2ind

search: sub2ind subplot2grid



```
sub2ind(dims, i, j, k...) -> index
```

The inverse of `ind2sub`, returns the linear index corresponding to the provided subscripts.


In [362]:
ret = ind2sub(size(r), indmin(fr))
fr[ret...] = Inf
ret

(20,1)

In [363]:
word = "australia"
uu=utilisation[word]
lp = all_logprobs[word]
kept_indexes = find(uu)
rlp=exp(lp[:,kept_indexes])

145×19 Array{Float64,2}:
 0.000502276  0.000316107  0.000428923  …  0.000876247  0.00137192 
 0.000829902  0.000218465  0.000576839     0.000678487  0.00123923 
 9.79935e-5   1.25864e-5   2.40151e-5      0.000105339  0.000150048
 9.94962e-5   1.50496e-5   2.35071e-5      0.000108355  0.000155001
 0.000220705  6.96376e-5   0.000315089     0.000562183  0.000624032
 7.086e-5     5.47539e-5   0.000137396  …  1.74319e-5   0.000257753
 0.00843422   0.00143562   0.00326022      0.00939931   0.0069828  
 0.000713116  8.09506e-5   9.55926e-5      0.000259066  0.000331115
 0.00148565   0.000260937  0.000223807     0.00107824   0.000617886
 0.00281858   0.000307393  0.00257715      0.00480165   0.00219697 
 0.000334445  5.06608e-5   0.000275592  …  0.00108302   0.000175337
 0.000343419  0.000145396  0.000585987     0.000738764  0.00228387 
 0.00293491   0.00264198   0.00325985      0.00296087   0.00467582 
 ⋮                                      ⋱                          
 0.0006459    0.0001957

In [196]:
nearests = """1	[Pair{Any,Any}(("ireland",16),0.64708966f0),Pair{Any,Any}(("britain",16),0.64880353f0),Pair{Any,Any}(("especially",9),0.6513231f0),Pair{Any,Any}(("provided",15),0.67011666f0),Pair{Any,Any}(("particularly",20),0.6725949f0)]
2	[Pair{Any,Any}(("deaths",18),0.6309011f0),Pair{Any,Any}(("sir",20),0.6614016f0),Pair{Any,Any}(("morgan",1),0.6741953f0),Pair{Any,Any}(("west",18),0.6777778f0),Pair{Any,Any}(("isbn",5),0.67834324f0)]
3	[Pair{Any,Any}(("prime",13),0.2473808f0),Pair{Any,Any}(("minister",20),0.31629658f0),Pair{Any,Any}(("prime",1),0.32216263f0),Pair{Any,Any}(("ministers",4),0.34331042f0),Pair{Any,Any}(("minister",3),0.36456484f0)]
4	[Pair{Any,Any}(("list",8),0.59148026f0),Pair{Any,Any}(("and",20),0.614841f0),Pair{Any,Any}(("official",13),0.624194f0),Pair{Any,Any}(("general",18),0.62567335f0),Pair{Any,Any}(("members",15),0.629411f0)]
5	[Pair{Any,Any}(("western",13),0.4191454f0),Pair{Any,Any}(("town",10),0.42082667f0),Pair{Any,Any}(("queensland",4),0.43156624f0),Pair{Any,Any}(("wales",18),0.45057023f0),Pair{Any,Any}(("south",12),0.45707417f0)]
6	[Pair{Any,Any}(("zealand",17),0.51816374f0),Pair{Any,Any}(("match",1),0.51989126f0),Pair{Any,Any}(("us",14),0.5360247f0),Pair{Any,Any}(("test",15),0.5406124f0),Pair{Any,Any}(("first",13),0.5431219f0)]
7	[Pair{Any,Any}(("cartoonist",16),0.647694f0),Pair{Any,Any}(("modernisation",1),0.6486087f0),Pair{Any,Any}(("april",13),0.66997445f0),Pair{Any,Any}(("becoming",20),0.6734446f0),Pair{Any,Any}(("american",8),0.68248886f0)]
8	[Pair{Any,Any}(("matters",20),0.66755116f0),Pair{Any,Any}(("ourselves",1),0.6802366f0),Pair{Any,Any}(("whites",2),0.68125737f0),Pair{Any,Any}(("peace",6),0.68372583f0),Pair{Any,Any}(("more",6),0.68429744f0)]
9	[Pair{Any,Any}(("south",12),0.4463454f0),Pair{Any,Any}(("wales",19),0.4847467f0),Pair{Any,Any}(("new",3),0.5076965f0),Pair{Any,Any}(("zealand",17),0.51473045f0),Pair{Any,Any}(("victoria",11),0.51839817f0)]
10	[Pair{Any,Any}(("aclu",4),0.6944263f0),Pair{Any,Any}(("affects",1),0.69619596f0),Pair{Any,Any}(("requested",17),0.69798505f0),Pair{Any,Any}(("enhanced",19),0.7001114f0),Pair{Any,Any}(("duchy",1),0.70312595f0)]
11	[Pair{Any,Any}(("won",12),0.67440736f0),Pair{Any,Any}(("the",6),0.6763311f0),Pair{Any,Any}(("england",14),0.6785213f0),Pair{Any,Any}(("bishops",13),0.6839303f0),Pair{Any,Any}(("city",7),0.6852726f0)]
12	[Pair{Any,Any}(("eastern",1),0.45826256f0),Pair{Any,Any}(("india",12),0.48450494f0),Pair{Any,Any}(("in",1),0.48777324f0),Pair{Any,Any}(("central",19),0.4917227f0),Pair{Any,Any}(("canada",3),0.49812436f0)]
13	[Pair{Any,Any}(("eight",3),0.6424203f0),Pair{Any,Any}(("b",8),0.66651416f0),Pair{Any,Any}(("nsw",1),0.6762165f0),Pair{Any,Any}(("three",4),0.684096f0),Pair{Any,Any}(("nine",6),0.6855695f0)]
14	[Pair{Any,Any}(("south",17),0.34426063f0),Pair{Any,Any}(("japan",14),0.37043744f0),Pair{Any,Any}(("africa",7),0.3789521f0),Pair{Any,Any}(("and",6),0.38012308f0),Pair{Any,Any}(("east",9),0.3821984f0)]
15	[Pair{Any,Any}(("broke",1),0.6366043f0),Pair{Any,Any}(("july",5),0.6627748f0),Pair{Any,Any}(("zealand",17),0.6700146f0),Pair{Any,Any}(("question",20),0.6760824f0),Pair{Any,Any}(("the",11),0.67849857f0)]
16	[Pair{Any,Any}(("advance",6),0.48215127f0),Pair{Any,Any}(("canada",20),0.5794129f0),Pair{Any,Any}(("britain",20),0.5893681f0),Pair{Any,Any}(("france",9),0.60055745f0),Pair{Any,Any}(("germany",6),0.6300453f0)]
17	[Pair{Any,Any}(("australian",12),0.42347747f0),Pair{Any,Any}(("international",20),0.44074863f0),Pair{Any,Any}(("england",11),0.47114956f0),Pair{Any,Any}(("uk",4),0.47835565f0),Pair{Any,Any}(("an",3),0.47924346f0)]
18	[Pair{Any,Any}(("zealand",12),0.18529892f0),Pair{Any,Any}(("new",3),0.24071127f0),Pair{Any,Any}(("canada",3),0.2889933f0),Pair{Any,Any}(("kingdom",6),0.36203885f0),Pair{Any,Any}(("netherlands",18),0.38124573f0)]
19	[Pair{Any,Any}(("many",8),0.43426085f0),Pair{Any,Any}(("in",15),0.47859168f0),Pair{Any,Any}(("and",20),0.48893946f0),Pair{Any,Any}(("a",11),0.4949652f0),Pair{Any,Any}(("uk",14),0.4982586f0)]
20	[Pair{Any,Any}(("europe",18),0.48324925f0),Pair{Any,Any}(("countries",18),0.49733496f0),Pair{Any,Any}(("canada",15),0.5158184f0),Pair{Any,Any}(("many",1),0.53822476f0),Pair{Any,Any}(("television",7),0.54350066f0)]"""
nearests =[replace(split(entry,"\t")[2],"Pair{Any,Any}","") for entry in split(nearests,"\n")]


20-element Array{String,1}:
 "[((\"ireland\",16),0.64708966f0),((\"britain\",16),0.64880353f0),((\"especially\",9),0.6513231f0),((\"provided\",15),0.67011666f0),((\"particularly\",20),0.6725949f0)]"
 "[((\"deaths\",18),0.6309011f0),((\"sir\",20),0.6614016f0),((\"morgan\",1),0.6741953f0),((\"west\",18),0.6777778f0),((\"isbn\",5),0.67834324f0)]"                        
 "[((\"prime\",13),0.2473808f0),((\"minister\",20),0.31629658f0),((\"prime\",1),0.32216263f0),((\"ministers\",4),0.34331042f0),((\"minister\",3),0.36456484f0)]"          
 "[((\"list\",8),0.59148026f0),((\"and\",20),0.614841f0),((\"official\",13),0.624194f0),((\"general\",18),0.62567335f0),((\"members\",15),0.629411f0)]"                   
 "[((\"western\",13),0.4191454f0),((\"town\",10),0.42082667f0),((\"queensland\",4),0.43156624f0),((\"wales\",18),0.45057023f0),((\"south\",12),0.45707417f0)]"            
 "[((\"zealand\",17),0.51816374f0),((\"match\",1),0.51989126f0),((\"us\",14),0.5360247f0),((\"test\",15),0.5406124f0)

In [419]:
exemplars(af::AffinityPropResult) = af.exemplars
exemplars(kf::KmedoidsResult) = kf.medoids
function print_clusters(af)
    true_examplars = kept_indexes[exemplars(af)]
    @show true_examplars 
    true_assignments = true_examplars[assignments(af)];
    @show true_assignments
    println("--")
    for true_exemplar_ii in true_examplars
        for (orignal_sense_ii, true_assignment_ii) in enumerate(true_assignments)
            true_original_sense_ii = kept_indexes[orignal_sense_ii]
            if true_assignment_ii==true_exemplar_ii
                if true_original_sense_ii==true_exemplar_ii
                    print("*")
                end
                println(nearests[true_original_sense_ii])
            end
        end
        println()
        
    end
end

print_clusters (generic function with 1 method)

In [364]:
dist = r
af=affinityprop(dists, display=:final, damp=0.5, maxiter=200)
print_clusters(af)

Affinity propagation converged with 44 iterations: 3 exemplars.
true_examplars = [2,10,11]
true_assignments = [10,2,11,11,10,10,10,10,10,11,10,2,2,10,2,2,2,2,2]
--
*[(("deaths",18),0.6309011f0),(("sir",20),0.6614016f0),(("morgan",1),0.6741953f0),(("west",18),0.6777778f0),(("isbn",5),0.67834324f0)]
[(("eight",3),0.6424203f0),(("b",8),0.66651416f0),(("nsw",1),0.6762165f0),(("three",4),0.684096f0),(("nine",6),0.6855695f0)]
[(("south",17),0.34426063f0),(("japan",14),0.37043744f0),(("africa",7),0.3789521f0),(("and",6),0.38012308f0),(("east",9),0.3821984f0)]
[(("advance",6),0.48215127f0),(("canada",20),0.5794129f0),(("britain",20),0.5893681f0),(("france",9),0.60055745f0),(("germany",6),0.6300453f0)]
[(("australian",12),0.42347747f0),(("international",20),0.44074863f0),(("england",11),0.47114956f0),(("uk",4),0.47835565f0),(("an",3),0.47924346f0)]
[(("zealand",12),0.18529892f0),(("new",3),0.24071127f0),(("canada",3),0.2889933f0),(("kingdom",6),0.36203885f0),(("netherlands",18),0.38124573f0)]
[

In [278]:
function scale_to_range(x, xs, ys)
    scaled_x = x-minimum(xs)/(maximum(xs)-minimum(xs))
    minimum(ys)+scaled_x.*(maximum(ys)-minimum(ys))
end

scale_to_range (generic function with 1 method)

In [301]:
dists

19×19 Array{Float64,2}:
  0.0945462    1.50389   -0.0517176  …  -0.865246   -1.16101   -0.525682 
  1.50389     -0.231096  -0.923457       2.10792     2.28134    2.38486  
 -0.0517176   -0.923457   0.0584093      0.680004    0.339451   0.970045 
 -1.20251      1.66703   -0.226216      -0.0514805  -1.25396   -0.548043 
 -0.558373     2.01014    0.645534      -1.07327     0.196188  -0.31214  
 -0.00866698  -0.340877  -0.512689   …   0.438067    0.743241   0.0395598
 -0.0996641   -0.422912  -0.969897       0.790198    0.137412   0.557045 
  0.827596    -0.883476  -0.83002        0.39127     1.81357    1.55693  
  0.0496075   -0.361393  -0.72681        0.98309     0.55284    0.416044 
  0.887543    -1.4117    -0.967592       1.31207     1.61169    1.3724   
 -1.04526      1.63166    0.635853   …  -0.809929   -0.58368   -0.823253 
  0.373626    -0.876751  -1.25697        1.20308     0.78673    1.58676  
 -1.04307      1.60449    0.13605       -1.14053    -0.657669  -0.428266 
 -0.700976    

In [484]:
odists=pairwise(CorrDist(),rlp,rlp)
dists=(odists-mean(odists))/std(odists)
dists[eye(Bool,size(dists,1))]=(mean(rlp,1)-mean(rlp))/std(rlp)

af=affinityprop(dists, display=:final, damp=0.5, maxiter=200)
print_clusters(af)

Affinity propagation converged with 40 iterations: 2 exemplars.
true_examplars = [2,17]
true_assignments = [2,2,17,2,2,17,17,17,17,17,2,17,2,2,2,17,2,2,2]
--
[(("ireland",16),0.64708966f0),(("britain",16),0.64880353f0),(("especially",9),0.6513231f0),(("provided",15),0.67011666f0),(("particularly",20),0.6725949f0)]
*[(("deaths",18),0.6309011f0),(("sir",20),0.6614016f0),(("morgan",1),0.6741953f0),(("west",18),0.6777778f0),(("isbn",5),0.67834324f0)]
[(("list",8),0.59148026f0),(("and",20),0.614841f0),(("official",13),0.624194f0),(("general",18),0.62567335f0),(("members",15),0.629411f0)]
[(("western",13),0.4191454f0),(("town",10),0.42082667f0),(("queensland",4),0.43156624f0),(("wales",18),0.45057023f0),(("south",12),0.45707417f0)]
[(("eastern",1),0.45826256f0),(("india",12),0.48450494f0),(("in",1),0.48777324f0),(("central",19),0.4917227f0),(("canada",3),0.49812436f0)]
[(("south",17),0.34426063f0),(("japan",14),0.37043744f0),(("africa",7),0.3789521f0),(("and",6),0.38012308f0),(("east",9),0.3

In [485]:
vlp=rlp.-maximum(rlp,2);
dists = pairwise(CorrDist(),vlp,vlp)
scaled_preference = scale_to_range(mean(vlp,1), vlp, dists)
#dists[eye(Bool,size(dists,1))]=scaled_preference
#6*minimum(dists)#+mean(rlp,1)*0.3*(maximum(dists)-minimum(dists))
af=affinityprop(dists, display=:final, damp=0.5, maxiter=200)
print_clusters(af)


Affinity propagation converged with 33 iterations: 2 exemplars.
true_examplars = [5,9]
true_assignments = [9,5,5,9,5,9,9,9,9,5,9,5,9,9,9,9,9,9,9]
--
[(("deaths",18),0.6309011f0),(("sir",20),0.6614016f0),(("morgan",1),0.6741953f0),(("west",18),0.6777778f0),(("isbn",5),0.67834324f0)]
[(("prime",13),0.2473808f0),(("minister",20),0.31629658f0),(("prime",1),0.32216263f0),(("ministers",4),0.34331042f0),(("minister",3),0.36456484f0)]
*[(("western",13),0.4191454f0),(("town",10),0.42082667f0),(("queensland",4),0.43156624f0),(("wales",18),0.45057023f0),(("south",12),0.45707417f0)]
[(("won",12),0.67440736f0),(("the",6),0.6763311f0),(("england",14),0.6785213f0),(("bishops",13),0.6839303f0),(("city",7),0.6852726f0)]
[(("eight",3),0.6424203f0),(("b",8),0.66651416f0),(("nsw",1),0.6762165f0),(("three",4),0.684096f0),(("nine",6),0.6855695f0)]

[(("ireland",16),0.64708966f0),(("britain",16),0.64880353f0),(("especially",9),0.6513231f0),(("provided",15),0.67011666f0),(("particularly",20),0.6725949f0)]
[((

In [486]:
wv = hcat(ee.embedding[word][find(uu.>0)]...)
odists = pairwise(CosineDist(),wv,wv)
dists=(odists-mean(odists))/std(odists)
dists[eye(Bool,size(dists,1))]=(mean(rlp,1)-mean(rlp))/std(rlp)

af=affinityprop(dists, display=:final, damp=0.5, maxiter=200)
print_clusters(af)

Affinity propagation converged with 44 iterations: 3 exemplars.
true_examplars = [2,10,11]
true_assignments = [10,2,11,11,10,10,10,10,10,11,10,2,2,10,2,2,2,2,2]
--
*[(("deaths",18),0.6309011f0),(("sir",20),0.6614016f0),(("morgan",1),0.6741953f0),(("west",18),0.6777778f0),(("isbn",5),0.67834324f0)]
[(("eight",3),0.6424203f0),(("b",8),0.66651416f0),(("nsw",1),0.6762165f0),(("three",4),0.684096f0),(("nine",6),0.6855695f0)]
[(("south",17),0.34426063f0),(("japan",14),0.37043744f0),(("africa",7),0.3789521f0),(("and",6),0.38012308f0),(("east",9),0.3821984f0)]
[(("advance",6),0.48215127f0),(("canada",20),0.5794129f0),(("britain",20),0.5893681f0),(("france",9),0.60055745f0),(("germany",6),0.6300453f0)]
[(("australian",12),0.42347747f0),(("international",20),0.44074863f0),(("england",11),0.47114956f0),(("uk",4),0.47835565f0),(("an",3),0.47924346f0)]
[(("zealand",12),0.18529892f0),(("new",3),0.24071127f0),(("canada",3),0.2889933f0),(("kingdom",6),0.36203885f0),(("netherlands",18),0.38124573f0)]
[

In [ ]:

function kldist(logprobs)
    n_samples, n_models = size(logprobs)
    distence_matrix = Array(Float64,(n_models,n_models))
    for p_i in 1:n_models
        for q_i in 1:n_models
            distence_matrix[p_i,q_i] = corr_dist((logprobs[:,p_i]),(logprobs[:,q_i]))
        end
    end
    distence_matrix
end

In [ ]:
kldist(all_logprobs["a"])

In [ ]:
kldist(all_logprobs["mutual"])

In [ ]:
kldist(all_logprobs["for"])

In [ ]:
all_logprobs["about"]

In [ ]:
all_logprobs["for"]