In [1]:
using WordEmbeddings, SoftmaxClassifier
using Utils
using Query
using Base.Collections
using WordStreams

using Clustering
using Distances
using Iterators

In [2]:
ee = restore("models/ss/text8_200__i5.model");

In [511]:
function print_nearest_words(word)
    ret = []
    for ii in 1:length(ee.embedding[word])
        nears = Query.find_nearest_words(ee, word, ii)
        println(ii,"\t", nears)
        println()
        push!(ret,nears)
    end
    return ret
end

print_nearest_words (generic function with 1 method)

In [140]:
print_nearest_words("a")

1	[Pair{Any,Any}(("with",12),0.36149585f0),Pair{Any,Any}(("on",5),0.36803174f0),Pair{Any,Any}(("by",11),0.37724584f0),Pair{Any,Any}(("s",17),0.4047312f0),Pair{Any,Any}(("extensive",20),0.4205863f0)]

2	[Pair{Any,Any}(("the",7),0.1644544f0),Pair{Any,Any}(("is",4),0.22158211f0),Pair{Any,Any}(("an",12),0.23381048f0),Pair{Any,Any}(("or",5),0.2376225f0),Pair{Any,Any}(("this",17),0.25288576f0)]

3	[Pair{Any,Any}(("the",19),0.24315614f0),Pair{Any,Any}(("an",11),0.26751918f0),Pair{Any,Any}(("and",4),0.2919441f0),Pair{Any,Any}(("in",4),0.33031344f0),Pair{Any,Any}(("with",9),0.33774894f0)]

4	[Pair{Any,Any}(("people",12),0.44990408f0),Pair{Any,Any}(("wide",16),0.45150584f0),Pair{Any,Any}(("numbers",17),0.45552343f0),Pair{Any,Any}(("of",17),0.4563133f0),Pair{Any,Any}(("large",14),0.45695388f0)]

5	[Pair{Any,Any}(("such",3),0.45609432f0),Pair{Any,Any}(("they",10),0.45987588f0),Pair{Any,Any}(("for",14),0.47111166f0),Pair{Any,Any}(("the",12),0.47988933f0),Pair{Any,Any}(("an",9),0.48544067f0)]

6	[Pa

In [ ]:
print_nearest_words("kind")

In [785]:
nearests = print_nearest_words("race")

1	[Pair{Any,Any}(("latino",4),0.24718815f0),Pair{Any,Any}(("hispanic",9),0.3567357f0),Pair{Any,Any}(("any",8),0.3594371f0),Pair{Any,Any}(("population",8),0.36768758f0),Pair{Any,Any}(("mixed",20),0.4379238f0)]

2	[Pair{Any,Any}(("racing",16),0.42366487f0),Pair{Any,Any}(("racing",17),0.43566388f0),Pair{Any,Any}(("car",5),0.4631629f0),Pair{Any,Any}(("races",13),0.47124088f0),Pair{Any,Any}(("prix",15),0.48116124f0)]

3	[Pair{Any,Any}(("rather",16),0.59287184f0),Pair{Any,Any}(("lose",1),0.61896396f0),Pair{Any,Any}(("whether",16),0.6301135f0),Pair{Any,Any}(("world",13),0.637156f0),Pair{Any,Any}(("doing",11),0.63731027f0)]

4	[Pair{Any,Any}(("racial",15),0.61707014f0),Pair{Any,Any}(("mi",13),0.6285727f0),Pair{Any,Any}(("dearborn",1),0.6412274f0),Pair{Any,Any}(("lexington",1),0.6462248f0),Pair{Any,Any}(("louisville",1),0.6473862f0)]

5	[Pair{Any,Any}(("that",5),0.661414f0),Pair{Any,Any}(("bigfoot",3),0.68456054f0),Pair{Any,Any}(("thought",14),0.69747275f0),Pair{Any,Any}(("conventions",20),0.69

20-element Array{Any,1}:
 [Pair{Any,Any}(("latino",4),0.24718815f0),Pair{Any,Any}(("hispanic",9),0.3567357f0),Pair{Any,Any}(("any",8),0.3594371f0),Pair{Any,Any}(("population",8),0.36768758f0),Pair{Any,Any}(("mixed",20),0.4379238f0)]                     
 [Pair{Any,Any}(("racing",16),0.42366487f0),Pair{Any,Any}(("racing",17),0.43566388f0),Pair{Any,Any}(("car",5),0.4631629f0),Pair{Any,Any}(("races",13),0.47124088f0),Pair{Any,Any}(("prix",15),0.48116124f0)]                        
 [Pair{Any,Any}(("rather",16),0.59287184f0),Pair{Any,Any}(("lose",1),0.61896396f0),Pair{Any,Any}(("whether",16),0.6301135f0),Pair{Any,Any}(("world",13),0.637156f0),Pair{Any,Any}(("doing",11),0.63731027f0)]                       
 [Pair{Any,Any}(("racial",15),0.61707014f0),Pair{Any,Any}(("mi",13),0.6285727f0),Pair{Any,Any}(("dearborn",1),0.6412274f0),Pair{Any,Any}(("lexington",1),0.6462248f0),Pair{Any,Any}(("louisville",1),0.6473862f0)]                  
 [Pair{Any,Any}(("that",5),0.661414f0),Pair{Any,Any}(("bigf

In [ ]:
print_nearest_words("dying")

In [ ]:
print_nearest_words("fear")

In [ ]:
print_nearest_words("mouse")

In [ ]:
print_nearest_words("video")

In [ ]:
print_nearest_words("phone")

In [ ]:
print_nearest_words("came")

In [ ]:
print_nearest_words("come")

In [ ]:
print_nearest_words("define")

In [148]:
print_nearest_words("australia")

1	[Pair{Any,Any}(("ireland",16),0.64708966f0),Pair{Any,Any}(("britain",16),0.64880353f0),Pair{Any,Any}(("especially",9),0.6513231f0),Pair{Any,Any}(("provided",15),0.67011666f0),Pair{Any,Any}(("particularly",20),0.6725949f0)]

2	[Pair{Any,Any}(("deaths",18),0.6309011f0),Pair{Any,Any}(("sir",20),0.6614016f0),Pair{Any,Any}(("morgan",1),0.6741953f0),Pair{Any,Any}(("west",18),0.6777778f0),Pair{Any,Any}(("isbn",5),0.67834324f0)]

3	[Pair{Any,Any}(("prime",13),0.2473808f0),Pair{Any,Any}(("minister",20),0.31629658f0),Pair{Any,Any}(("prime",1),0.32216263f0),Pair{Any,Any}(("ministers",4),0.34331042f0),Pair{Any,Any}(("minister",3),0.36456484f0)]

4	[Pair{Any,Any}(("list",8),0.59148026f0),Pair{Any,Any}(("and",20),0.614841f0),Pair{Any,Any}(("official",13),0.624194f0),Pair{Any,Any}(("general",18),0.62567335f0),Pair{Any,Any}(("members",15),0.629411f0)]

5	[Pair{Any,Any}(("western",13),0.4191454f0),Pair{Any,Any}(("town",10),0.42082667f0),Pair{Any,Any}(("queensland",4),0.43156624f0),Pair{Any,Any}(("wal

In [552]:
nearests = print_nearest_words("states")

1	[Pair{Any,Any}(("states",10),0.44406152f0),Pair{Any,Any}(("states",13),0.44755912f0),Pair{Any,Any}(("kingdom",1),0.44778913f0),Pair{Any,Any}(("america",9),0.45211357f0),Pair{Any,Any}(("united",15),0.45302373f0)]

2	[Pair{Any,Any}(("nations",20),0.3316921f0),Pair{Any,Any}(("countries",1),0.35931808f0),Pair{Any,Any}(("and",6),0.3976617f0),Pair{Any,Any}(("of",6),0.4001304f0),Pair{Any,Any}(("united",4),0.4064538f0)]

3	[Pair{Any,Any}(("united",14),0.3348794f0),Pair{Any,Any}(("constitution",1),0.34970987f0),Pair{Any,Any}(("states",14),0.3956474f0),Pair{Any,Any}(("u",7),0.40181845f0),Pair{Any,Any}(("states",5),0.44029248f0)]

4	[Pair{Any,Any}(("kingdom",1),0.2919402f0),Pair{Any,Any}(("united",13),0.30385137f0),Pair{Any,Any}(("constitution",1),0.3695827f0),Pair{Any,Any}(("that",3),0.37023968f0),Pair{Any,Any}(("federal",20),0.41255087f0)]

5	[Pair{Any,Any}(("united",12),0.35347873f0),Pair{Any,Any}(("states",8),0.355218f0),Pair{Any,Any}(("states",7),0.3958528f0),Pair{Any,Any}(("states",13),0.

20-element Array{Any,1}:
 [Pair{Any,Any}(("states",10),0.44406152f0),Pair{Any,Any}(("states",13),0.44755912f0),Pair{Any,Any}(("kingdom",1),0.44778913f0),Pair{Any,Any}(("america",9),0.45211357f0),Pair{Any,Any}(("united",15),0.45302373f0)]                
 [Pair{Any,Any}(("nations",20),0.3316921f0),Pair{Any,Any}(("countries",1),0.35931808f0),Pair{Any,Any}(("and",6),0.3976617f0),Pair{Any,Any}(("of",6),0.4001304f0),Pair{Any,Any}(("united",4),0.4064538f0)]                           
 [Pair{Any,Any}(("united",14),0.3348794f0),Pair{Any,Any}(("constitution",1),0.34970987f0),Pair{Any,Any}(("states",14),0.3956474f0),Pair{Any,Any}(("u",7),0.40181845f0),Pair{Any,Any}(("states",5),0.44029248f0)]                    
 [Pair{Any,Any}(("kingdom",1),0.2919402f0),Pair{Any,Any}(("united",13),0.30385137f0),Pair{Any,Any}(("constitution",1),0.3695827f0),Pair{Any,Any}(("that",3),0.37023968f0),Pair{Any,Any}(("federal",20),0.41255087f0)]               
 [Pair{Any,Any}(("united",12),0.35347873f0),Pair{Any,Any}((

In [789]:
exemplars(af::AffinityPropResult) = af.exemplars
exemplars(kf::KmedoidsResult) = kf.medoids
function print_clusters(af::Clustering.ClusteringResult)
    true_examplars = kept_indexes[exemplars(af)]
    @show true_examplars 
    true_assignments = true_examplars[assignments(af)];
    @show true_assignments
    println("--")
    for true_exemplar_ii in true_examplars
        for (orignal_sense_ii, true_assignment_ii) in enumerate(true_assignments)
            true_original_sense_ii = kept_indexes[orignal_sense_ii]
            if true_assignment_ii==true_exemplar_ii
                if true_original_sense_ii==true_exemplar_ii
                    print("*")
                end
                println(nearests[true_original_sense_ii])
            end
        end
        println()
        
    end
end

function print_clusters(ass::Vector, nearests_words)
    for grp in groupby(first, sort(collect(zip(ass,nearests_words)), by=first))
        for (grp_id, nearests) in grp
            println(nearests) 
        end
        println()
    end
    
end

print_clusters (generic function with 4 methods)

[Pair{Any,Any}(("states",10),0.44406152f0),Pair{Any,Any}(("states",13),0.44755912f0),Pair{Any,Any}(("kingdom",1),0.44778913f0),Pair{Any,Any}(("america",9),0.45211357f0),Pair{Any,Any}(("united",15),0.45302373f0)]
[Pair{Any,Any}(("nations",20),0.3316921f0),Pair{Any,Any}(("countries",1),0.35931808f0),Pair{Any,Any}(("and",6),0.3976617f0),Pair{Any,Any}(("of",6),0.4001304f0),Pair{Any,Any}(("united",4),0.4064538f0)]
[Pair{Any,Any}(("united",14),0.3348794f0),Pair{Any,Any}(("constitution",1),0.34970987f0),Pair{Any,Any}(("states",14),0.3956474f0),Pair{Any,Any}(("u",7),0.40181845f0),Pair{Any,Any}(("states",5),0.44029248f0)]
[Pair{Any,Any}(("kingdom",1),0.2919402f0),Pair{Any,Any}(("united",13),0.30385137f0),Pair{Any,Any}(("constitution",1),0.3695827f0),Pair{Any,Any}(("that",3),0.37023968f0),Pair{Any,Any}(("federal",20),0.41255087f0)]
[Pair{Any,Any}(("united",12),0.35347873f0),Pair{Any,Any}(("states",8),0.355218f0),Pair{Any,Any}(("states",7),0.3958528f0),Pair{Any,Any}(("states",13),0.40636587f0),Pa

In [ ]:
using LightXML
using Pipe
Base.iteratorsize(::Type{LightXML.XMLNodeIter})=Base.SizeUnknown()
Base.iteratorsize(::Type{LightXML.XMLElementIter})=Base.SizeUnknown()

In [ ]:
function load_semeval(filename)

    function get_wsd_case(instance_node, preprocess=lowercase)
        word=""
        context=String[]
        for node in instance_node |> child_nodes
            if is_elementnode(node)
                @assert word==""
                word = node |>child_nodes |> first |> string |> preprocess |> strip
            else
                @assert(node|>is_textnode)
                append!(context, node|>string|>preprocess|>split)
            end
        end
        @assert word!=""
        word, context
    end

    xdoc = parse_file(filename)
    
    xroot = root(xdoc);  # an instance of XMLElement
    nodes = Base.Flatten(child_elements(instance)  for instance in child_elements(xroot)) 
    map(get_wsd_case, nodes) |> collect    
end

In [ ]:
#cases = load_semeval("./data/corpora/semeval2007t2/trial_data/English.LS.txt");

# What makes a particular set of sense embeddings good?
Goal here is to define a fittness function for a set of sentence embeddings.  

THis is loosely similar to the criteria for a good set of clusters. 
A good clustering has small varience within the class;
and we write:
$$g_{fit}(Z=\{z_1,z_2,...,z_k\})=\dfrac{1}{|Z|}{\sum\limits_{\forall z \in Z}}\:{\sum\limits_{\forall x\in \mathcal{C}(z)}{\left(x-z\right)^2}}$$

A good sense embeddings assigned a high probability of its context, when it is the highest, and a low probability of its context when it is not highest -- forcing each sense to be different.



In [4]:
function perplexity(ee, cases, banned_senses=Dict())
    sum_of_logprobs = 0.0
    nwords = 0
    for case in cases
        w_ind = length(case)÷2
        word = case[w_ind]
        haskey(ee.embedding, word) || continue
        context = case[[1:w_ind-1;w_ind+1:end]]
        
        best_logprob = -Inf
        for (s_id, s_emb) in enumerate(ee.embedding[word])
            haskey(banned_senses, word) && s_id in banned_senses[word] && continue
            best_logprob = max(best_logprob, 
                logprob_of_context(ee,context, s_emb; 
            skip_oov=true, normalise_over_length=true ))   
        end
        nwords+=1
        sum_of_logprobs+=best_logprob
    end
    @show(sum_of_logprobs)
    @show(nwords)
    cross_entropy = -1.0/nwords * sum_of_logprobs 
    @show(cross_entropy)
    exp(cross_entropy)
end

perplexity (generic function with 2 methods)

In [ ]:
perplexity(ee,cases[end÷2:end])

In [ ]:
exp(-4.333793639526367e6 *(-1/548704))
#Maximum Perp = 2692.5282875803277
#Minimum Perp = 22033.97695332202
#Mean Perp = 7596.212357052384
#Median Perp = 7550.162665209774

In [311]:


#cases = sliding_window( words_of("data/corpora/text8/text8"))|> collect 
#case = case[1:end÷10]
cases = sliding_window( words_of("../test/data/text8_tiny"))|> collect 

all_logprobs = DefaultDict(Any,Any, ()->[])
for case in cases
    w_ind = length(case)÷2
    word = case[w_ind]
    haskey(ee.embedding, word) || continue
    context = case[[1:w_ind-1;w_ind+1:end]]
    probs = Float64[logprob_of_context(ee, context, sense_embed; skip_oov=true, normalise_over_length=true)
                    for  sense_embed in ee.embedding[word]]
    push!(all_logprobs[word], probs)
end
all_logprobs = Dict([word=>hcat(logprobs_list...)' for (word,logprobs_list) in all_logprobs]) 
utilisation = Dict(([word=>sum(logprobs_list.==maximum(logprobs_list,2),1)[:] for (word,logprobs_list) in all_logprobs]) )

    ""


""

In [706]:
logprobs_t = []
cases = sliding_window( words_of("data/corpora/text8/text8"))|> collect 
for case in cases
    w_ind = length(case)÷2
    word = case[w_ind]
    if word!= "states" 
        continue
    end
    context = case[[1:w_ind-1;w_ind+1:end]]
    probs = Float64[logprob_of_context(ee, context, sense_embed; skip_oov=true, normalise_over_length=true)
                    for  sense_embed in ee.embedding[word]]
    push!(logprobs_t, probs)
end
""

""

In [707]:
logprobs_t = hcat(logprobs_t...)'
utilisation_t = sum(logprobs_t.==maximum(logprobs_t,2),1)[:]
cost_to_replace_t=zeros(size(logprobs_t,2),size(logprobs_t,2))
for case in 1:size(logprobs_t,1)
    best_sense_logprob, best_sense = findmax(logprobs_t[case,:])
    #Only the best sense count for scored -- the is no cost to replace 2nd best with third best
    for r_sense in 1:size(logprobs_t,2)
        cost_to_replace_t[best_sense, r_sense]=best_sense_logprob-logprobs_t[case,r_sense]
    end
end
balanced_cost_to_replace_t = cost_to_replace_t./utilisation_t;
""

""

20×20 Array{Float64,2}:
 0.0          0.00259316   1.72844e-6   0.000340356  …  0.00265254   0.00123143   0.00167258 
 0.000568332  0.0          0.00114708   0.0011345       0.000758685  5.55439e-5   0.000568204
 0.00119014   0.00281492   0.0          0.0012742       0.00398878   0.00235758   0.00169803 
 0.00228625   0.0023039    0.00172409   0.0             0.00175399   0.00209656   0.00177017 
 0.00273903   0.00218354   0.00216159   0.00181441      0.00286604   0.00017541   0.00181901 
 0.00244187   0.00497829   0.00186434   0.00196877   …  0.00411306   0.00189014   0.0010665  
 0.00230155   0.00274571   0.00121283   0.00155977      0.00146125   0.00172299   0.00175618 
 0.00160522   0.000891157  0.00103197   0.00107927      0.00108873   0.00130678   0.00138947 
 0.00211943   0.00190314   0.000985311  0.0013332       0.00137605   0.00135961   0.000304896
 0.00272603   0.00227114   0.00412788   0.00413607      0.00425592   0.00212122   0.00209183 
 0.00123727   0.00118504   0.0002756

In [320]:
cost_to_replace = Dict()
for (word, logprobs) in all_logprobs
    cost_to_replace[word]=zeros(size(logprobs,2),size(logprobs,2))
    for case in 1:size(logprobs,1)
        best_cutree(res; k=3)sense_logprob, best_sense = findmax(logprobs[case,:])
        #Only the best sense count for scored -- the is no cost to replace 2nd best with third best
        for r_sense in 1:size(logprobs,2)
            cost_to_replace[word][best_sense, r_sense]=best_sense_logprob-logprobs[case,r_sense]
        end
    end
end

In [ ]:
balanced_cost_to_replace = [w=>cost_to_replace[w]./utilisation[w] for w in keys(cost_to_replace)]

In [617]:
function cost_of_selection(costs_to_replace, selection)
    remaining = trues(size(costs_to_replace,1))
    remaining[selection]=false
    costs = costs_to_replace[remaining,selection] #Replace the remaining, with one from the selection
    sum(minimum(costs,1))
end
function do_sel()
    sel = rand(Bool,size(fr,1))
    cost = cost_of_selection(fr,sel)*sum(sel)
    (cost, sel)
end
res = sort(map(x->do_sel(),1:100), by=first)

20-element Array{Int64,1}:
 13
 14
 18
 14
  3
  7
 16
 16
 12
  7
 15
 17
 30
 16
  5
 16
  6
 12
 10
 13

In [687]:
all_logprobs["states"][:,14:17]

260×4 Array{Float64,2}:
  -6.93954   -8.40331  -6.94505   -5.35008
  -9.18896   -7.47634  -7.10574   -8.69868
  -7.365     -7.47556  -6.93841   -7.0167 
  -5.80931   -6.44539  -5.61956   -6.23427
  -8.83859   -7.91678  -7.53123   -8.18826
  -7.97478   -8.19579  -7.45531   -7.50454
  -8.03757   -9.21313  -6.98435   -7.94053
  -9.34411   -8.93912  -7.49697   -7.96896
  -8.95274   -8.29018  -7.22205   -7.44596
  -8.72405   -8.71384  -7.15958   -7.6821 
  -9.99522  -10.1175   -8.26499   -8.45772
 -10.9193   -12.7234   -8.81467  -10.7818 
  -8.21155   -8.23402  -8.29086   -8.45409
  -6.00285   -7.99202  -6.69477   -5.99418
  -8.54823   -7.64786  -8.11895   -8.16745
  -5.623     -6.97974  -6.26292   -6.56344
  -4.89381   -5.91177  -5.29205   -5.34806
  -6.7213    -6.32349  -6.29308   -6.54681
  -5.52449   -8.00482  -6.8015    -6.41958
  -4.94973   -6.5732   -5.68415   -5.36573
  -4.0552    -5.90544  -4.96159   -5.10426
  -5.70673   -8.12159  -6.79458   -5.88191
  -5.30955   -8.10788  -6.7027

In [621]:
#r=cost_to_replace["australia"]
#fr=r[[1:7;9:end],[1:7;9:end]]
r=balanced_cost_to_replace["states"]
fr=r

20×20 Array{Float64,2}:
 0.0        0.0587818  0.0393284   …  0.0575837   0.0649955  0.0599064 
 0.020872   0.0        0.0430696      0.0355114   0.0399937  0.0451628 
 0.0322362  0.0720362  0.0            0.0263544   0.0880145  0.0407277 
 0.0841301  0.162502   0.0378458      0.159535    0.0690087  0.100165  
 0.0852226  0.176359   0.126625       0.110103    0.344913   0.154304  
 0.13675    0.244187   0.182746    …  0.221614    0.144887   0.106437  
 0.103061   0.0816779  0.0578923      0.065889    0.088529   0.0471512 
 0.0612716  0.0789135  0.0378339      0.0731455   0.0408738  0.103272  
 0.0552002  0.102638   0.0812077      0.0323311   0.0769999  0.0217095 
 0.0272605  0.0441812  0.00854792     0.150465    0.0807046  0.116225  
 0.021752   0.0839741  0.00339622  …  0.0328707   0.0610571  0.0246078 
 0.0487825  0.0195765  0.0563714      0.0031538   0.0282472  0.00777951
 0.0388073  0.0350128  0.0185816      0.0287042   0.0627525  0.0400582 
 0.0288672  0.051091   0.0569862      0.

In [723]:
ENV["LINES"] = 60
ENV["COLUMNS"] = 120
round([collect(0:20)'; [1:20 cost_to_replace_t]],4)

21×21 Array{Float64,2}:
  0.0  1.0     2.0     3.0     4.0     5.0     6.0     …  15.0     16.0     17.0     18.0     19.0     20.0   
  1.0  0.0     1.5896  0.0011  0.2086  1.3085  1.5466      2.6329   1.6878   1.4068   1.626    0.7549   1.0253
  2.0  0.3887  0.0     0.7846  0.776   0.099   1.1999      2.4154   0.9013   0.0387   0.5189   0.038    0.3887
  3.0  0.6903  1.6327  0.0     0.739   2.2917  1.3333      2.1456   1.3273   1.9834   2.3135   1.3674   0.9849
  4.0  2.1171  2.1334  1.5965  0.0     2.9255  1.4919      1.1928   0.5221   2.3247   1.6242   1.9414   1.6392
  5.0  1.2764  1.0175  1.0073  0.8455  0.0     1.7348  …   1.8095   1.2683   0.2717   1.3356   0.0817   0.8477
  6.0  1.6238  3.3106  1.2398  1.3092  2.2551  0.0         3.7752   2.4123   2.9939   2.7352   1.2569   0.7092
  7.0  1.7377  2.073   0.9157  1.1776  0.1329  0.3325      1.5492   1.0868   2.4699   1.1032   1.3009   1.3259
  8.0  1.4174  0.7869  0.9112  0.953   0.494   0.7006      1.1752   1.0802   0.9545   0.

In [721]:
res=hclust(fr+fr', :complete)


Clustering.Hclust{Float64}(19×2 Array{Int64,2}:
  -1  -10
  -2  -17
  -7  -13
 -11  -12
  -8  -16
  -3  -14
  -9  -20
 -19    4
  -4    6
   3    7
 -18    2
   5    8
   9   10
   1   11
  -5   -6
  12   13
  14   15
  16   17
 -15   18,[0.0344325,0.043985,0.0442829,0.0492461,0.0507868,0.0570288,0.0797652,0.0837546,0.119239,0.122771,0.123337,0.179103,0.210585,0.218257,0.286096,0.286859,0.319012,0.495037,1.34711],[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20],[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20],:complete)

In [722]:
print_clusters(cutree(res; k=10))

[Pair{Any,Any}(("states",10),0.44406152f0),Pair{Any,Any}(("states",13),0.44755912f0),Pair{Any,Any}(("kingdom",1),0.44778913f0),Pair{Any,Any}(("america",9),0.45211357f0),Pair{Any,Any}(("united",15),0.45302373f0)]
[Pair{Any,Any}(("united",17),0.31038278f0),Pair{Any,Any}(("kingdom",9),0.31697035f0),Pair{Any,Any}(("external",9),0.42242444f0),Pair{Any,Any}(("states",1),0.44406152f0),Pair{Any,Any}(("department",10),0.45678663f0)]

[Pair{Any,Any}(("nations",20),0.3316921f0),Pair{Any,Any}(("countries",1),0.35931808f0),Pair{Any,Any}(("and",6),0.3976617f0),Pair{Any,Any}(("of",6),0.4001304f0),Pair{Any,Any}(("united",4),0.4064538f0)]
[Pair{Any,Any}(("kingdom",5),0.24508834f0),Pair{Any,Any}(("canada",3),0.25505763f0),Pair{Any,Any}(("united",2),0.28550762f0),Pair{Any,Any}(("kingdom",6),0.29278505f0),Pair{Any,Any}(("france",2),0.30027217f0)]

[Pair{Any,Any}(("united",12),0.3402779f0),Pair{Any,Any}(("states",5),0.355218f0),Pair{Any,Any}(("kingdom",1),0.4408787f0),Pair{Any,Any}(("states",7),0.44342613f

20-element Array{Int64,1}:
 2
 2
 6
 6
 0
 2
 1
 3
 0
 3
 0
 0
 0
 0
 0
 0
 0
 1
 0
 2

In [788]:
nearests_t = nearests[utilisation[word].>0]

10-element Array{Any,1}:
 [Pair{Any,Any}(("latino",4),0.24718815f0),Pair{Any,Any}(("hispanic",9),0.3567357f0),Pair{Any,Any}(("any",8),0.3594371f0),Pair{Any,Any}(("population",8),0.36768758f0),Pair{Any,Any}(("mixed",20),0.4379238f0)]          
 [Pair{Any,Any}(("racing",16),0.42366487f0),Pair{Any,Any}(("racing",17),0.43566388f0),Pair{Any,Any}(("car",5),0.4631629f0),Pair{Any,Any}(("races",13),0.47124088f0),Pair{Any,Any}(("prix",15),0.48116124f0)]             
 [Pair{Any,Any}(("rather",16),0.59287184f0),Pair{Any,Any}(("lose",1),0.61896396f0),Pair{Any,Any}(("whether",16),0.6301135f0),Pair{Any,Any}(("world",13),0.637156f0),Pair{Any,Any}(("doing",11),0.63731027f0)]            
 [Pair{Any,Any}(("racial",15),0.61707014f0),Pair{Any,Any}(("mi",13),0.6285727f0),Pair{Any,Any}(("dearborn",1),0.6412274f0),Pair{Any,Any}(("lexington",1),0.6462248f0),Pair{Any,Any}(("louisville",1),0.6473862f0)]       
 [Pair{Any,Any}(("or",14),0.50824845f0),Pair{Any,Any}(("class",10),0.53170884f0),Pair{Any,Any}(("their"

In [786]:
word = "race"
ee_t=hcat(ee.embedding[word][utilisation[word].>0]...)
nkept = size(ee_t,2)
ENV["LINES"] = 60
ENV["COLUMNS"] = 120
round([collect(0:nkept)'; [1:nkept pairwise(Euclidean(),ee_t,ee_t)]],4)

11×11 Array{Float32,2}:
  0.0  1.0     2.0     3.0     4.0     5.0     6.0     7.0     8.0     9.0     10.0   
  1.0  0.0031  4.5625  4.3547  4.0789  3.8243  6.8595  5.4988  5.0731  7.21     6.6689
  2.0  4.5625  0.0     3.2904  3.1822  3.4471  6.2794  4.4256  4.2464  6.4913   5.7731
  3.0  4.3547  3.2904  0.0     3.6221  3.2226  6.0304  4.5658  4.9187  6.5388   5.4903
  4.0  4.0789  3.1822  3.6221  0.0     3.3323  6.2134  4.6593  4.6729  6.5902   5.7847
  5.0  3.8243  3.4471  3.2226  3.3323  0.0     5.7199  4.8996  4.3793  6.4411   5.5515
  6.0  6.8595  6.2794  6.0304  6.2134  5.7199  0.0     6.8263  7.0608  7.9933   7.1196
  7.0  5.4988  4.4256  4.5658  4.6593  4.8996  6.8263  0.0     5.5344  7.091    6.0682
  8.0  5.0731  4.2464  4.9187  4.6729  4.3793  7.0608  5.5344  0.0     7.2718   6.5333
  9.0  7.21    6.4913  6.5388  6.5902  6.4411  7.9933  7.091   7.2718  0.0028   7.9823
 10.0  6.6689  5.7731  5.4903  5.7847  5.5515  7.1196  6.0682  6.5333  7.9823   0.0   

In [794]:

res=hclust(pairwise(Euclidean(),ee_t,ee_t), :complete)
print_clusters(cutree(res; k=5), nearests_t)

[Pair{Any,Any}(("latino",4),0.24718815f0),Pair{Any,Any}(("hispanic",9),0.3567357f0),Pair{Any,Any}(("any",8),0.3594371f0),Pair{Any,Any}(("population",8),0.36768758f0),Pair{Any,Any}(("mixed",20),0.4379238f0)]
[Pair{Any,Any}(("racing",16),0.42366487f0),Pair{Any,Any}(("racing",17),0.43566388f0),Pair{Any,Any}(("car",5),0.4631629f0),Pair{Any,Any}(("races",13),0.47124088f0),Pair{Any,Any}(("prix",15),0.48116124f0)]
[Pair{Any,Any}(("rather",16),0.59287184f0),Pair{Any,Any}(("lose",1),0.61896396f0),Pair{Any,Any}(("whether",16),0.6301135f0),Pair{Any,Any}(("world",13),0.637156f0),Pair{Any,Any}(("doing",11),0.63731027f0)]
[Pair{Any,Any}(("racial",15),0.61707014f0),Pair{Any,Any}(("mi",13),0.6285727f0),Pair{Any,Any}(("dearborn",1),0.6412274f0),Pair{Any,Any}(("lexington",1),0.6462248f0),Pair{Any,Any}(("louisville",1),0.6473862f0)]
[Pair{Any,Any}(("or",14),0.50824845f0),Pair{Any,Any}(("class",10),0.53170884f0),Pair{Any,Any}(("their",5),0.5402069f0),Pair{Any,Any}(("alien",12),0.54398394f0),Pair{Any,Any}(

In [775]:
lr = -pairwise(Euclidean(),ee_t,ee_t)
lr[diagind(lr)]=minimum(lr[:,1])
res=affinityprop(lr,display=:final)
print_clusters(res.assignments)


Affinity propagation converged with 36 iterations: 3 exemplars.
[Pair{Any,Any}(("united",10),0.35612613f0),Pair{Any,Any}(("united",7),0.37133628f0),Pair{Any,Any}(("naval",1),0.3726164f0),Pair{Any,Any}(("navy",1),0.3882202f0),Pair{Any,Any}(("air",10),0.3950947f0)]
[Pair{Any,Any}(("united",10),0.24158186f0),Pair{Any,Any}(("force",6),0.3900885f0),Pair{Any,Any}(("states",6),0.40196747f0),Pair{Any,Any}(("army",4),0.4091851f0),Pair{Any,Any}(("united",11),0.43830615f0)]
[Pair{Any,Any}(("united",17),0.31038278f0),Pair{Any,Any}(("kingdom",9),0.31697035f0),Pair{Any,Any}(("external",9),0.42242444f0),Pair{Any,Any}(("states",1),0.44406152f0),Pair{Any,Any}(("department",10),0.45678663f0)]
[Pair{Any,Any}(("united",19),0.15835601f0),Pair{Any,Any}(("representatives",13),0.33551913f0),Pair{Any,Any}(("president",17),0.35693407f0),Pair{Any,Any}(("united",18),0.36217088f0),Pair{Any,Any}(("presidents",10),0.38865036f0)]
[Pair{Any,Any}(("united",7),0.34809154f0),Pair{Any,Any}(("united",3),0.36504114f0),Pair{

In [521]:
function repeat_kmediods(costs,k, rounds)
    best_total_cost=Inf
    best_res = nothing
    for round_ii in 1:rounds
        res = kmedoids(costs,k)
        if res.totalcost<best_total_cost
            best_res=res
        end
    end
    best_res
end

repeat_kmediods (generic function with 1 method)

In [522]:
p_score = Inf
@time for k in 2:size(fr,1)
    res = repeat_kmediods(fr,k,10)
    #@show silhouettes(res,fr)
    println(k,"\t")
    @show silhouettes(res,fr) |> mean
    @show res.totalcost
    
    @show p_score-res.totalcost
    p_score=res.totalcost
end

2	
silhouettes(res,fr) |> mean = 0.142719883829306
res.totalcost = 8.777563095092773
p_score - res.totalcost = Inf
3	
silhouettes(res,fr) |> mean = 0.16394798980616282
res.totalcost = 4.228608131408691
p_score - res.totalcost = 4.548954963684082
4	
silhouettes(res,fr) |> mean = 0.2890830686560084
res.totalcost = 3.068222999572754
p_score - res.totalcost = 1.1603851318359375
5	
silhouettes(res,fr) |> mean = 0.26202973071315416
res.totalcost = 2.445246696472168
p_score - res.totalcost = 0.6229763031005859
6	
silhouettes(res,fr) |> mean = 0.083011927544262
res.totalcost = 2.740838050842285
p_score - res.totalcost = -0.2955913543701172
7	
silhouettes(res,fr) |> mean = 0.24862801555476574
res.totalcost = 1.6659598350524902
p_score - res.totalcost = 1.074878215789795
8	
silhouettes(res,fr) |> mean = 0.3034015839544726
res.totalcost = 2.340773105621338
p_score - res.totalcost = -0.6748132705688477
9	
silhouettes(res,fr) |> mean = 0.38596367016033883
res.totalcost = 1.6469249725341797
p_score 

In [502]:
lr= r[[1:7;9:end],[1:7;9:end]]
lr[diagind(lr)]=0.0
sim=lr
silhouettes(affinityprop(maximum(lr).-lr,display=:final),lr)|> mean

Affinity propagation converged with 29 iterations: 19 exemplars.


1.0

In [524]:
silhouettes(affinityprop(r,display=:final),r)|> mean

Affinity propagation converged with 38 iterations: 3 exemplars.


-0.2619749908459709

In [498]:
?diagind

search: diagind disable_sigint SeedingAlgorithm



```
diagind(M[, k])
```

A `Range` giving the indices of the `k`th diagonal of the matrix `M`.


In [463]:
print_clusters(affinityprop(lr,display=:final))

Affinity propagation converged with 49 iterations: 5 exemplars.
true_examplars = [7,10,11,13,18]
true_assignments = [11,18,18,7,13,13,7,10,10,11,11,13,10,13,13,11,18,11,10]
--
[(("list",8),0.59148026f0),(("and",20),0.614841f0),(("official",13),0.624194f0),(("general",18),0.62567335f0),(("members",15),0.629411f0)]
*[(("cartoonist",16),0.647694f0),(("modernisation",1),0.6486087f0),(("april",13),0.66997445f0),(("becoming",20),0.6734446f0),(("american",8),0.68248886f0)]

[(("south",12),0.4463454f0),(("wales",19),0.4847467f0),(("new",3),0.5076965f0),(("zealand",17),0.51473045f0),(("victoria",11),0.51839817f0)]
*[(("aclu",4),0.6944263f0),(("affects",1),0.69619596f0),(("requested",17),0.69798505f0),(("enhanced",19),0.7001114f0),(("duchy",1),0.70312595f0)]
[(("south",17),0.34426063f0),(("japan",14),0.37043744f0),(("africa",7),0.3789521f0),(("and",6),0.38012308f0),(("east",9),0.3821984f0)]
[(("europe",18),0.48324925f0),(("countries",18),0.49733496f0),(("canada",15),0.5158184f0),(("many",1),0.53

In [483]:
print_clusters(kmedoids(fr,5))

true_examplars = [19,10,18,1,4]
true_assignments = [1,10,10,4,18,10,10,10,10,10,10,10,1,1,19,4,18,19,1]
--
[(("advance",6),0.48215127f0),(("canada",20),0.5794129f0),(("britain",20),0.5893681f0),(("france",9),0.60055745f0),(("germany",6),0.6300453f0)]
*[(("many",8),0.43426085f0),(("in",15),0.47859168f0),(("and",20),0.48893946f0),(("a",11),0.4949652f0),(("uk",14),0.4982586f0)]

[(("deaths",18),0.6309011f0),(("sir",20),0.6614016f0),(("morgan",1),0.6741953f0),(("west",18),0.6777778f0),(("isbn",5),0.67834324f0)]
[(("prime",13),0.2473808f0),(("minister",20),0.31629658f0),(("prime",1),0.32216263f0),(("ministers",4),0.34331042f0),(("minister",3),0.36456484f0)]
[(("zealand",17),0.51816374f0),(("match",1),0.51989126f0),(("us",14),0.5360247f0),(("test",15),0.5406124f0),(("first",13),0.5431219f0)]
[(("cartoonist",16),0.647694f0),(("modernisation",1),0.6486087f0),(("april",13),0.66997445f0),(("becoming",20),0.6734446f0),(("american",8),0.68248886f0)]
[(("south",12),0.4463454f0),(("wales",19),0.4847

In [418]:
res=kmedoids(fr,2)
res.assignments

19-element Array{Int64,1}:
 1
 2
 2
 1
 1
 2
 1
 2
 2
 2
 1
 2
 1
 1
 1
 1
 1
 1
 1

In [372]:
fr = r|> copy
fr[diagind(fr)]=1.0
fr[8,:]=Inf
fr[:,8]=Inf


Inf

In [371]:
?sub2ind

search: sub2ind subplot2grid



```
sub2ind(dims, i, j, k...) -> index
```

The inverse of `ind2sub`, returns the linear index corresponding to the provided subscripts.


In [362]:
ret = ind2sub(size(r), indmin(fr))
fr[ret...] = Inf
ret

(20,1)

In [363]:
word = "australia"
uu=utilisation[word]
lp = all_logprobs[word]
kept_indexes = find(uu)
rlp=exp(lp[:,kept_indexes])

145×19 Array{Float64,2}:
 0.000502276  0.000316107  0.000428923  …  0.000876247  0.00137192 
 0.000829902  0.000218465  0.000576839     0.000678487  0.00123923 
 9.79935e-5   1.25864e-5   2.40151e-5      0.000105339  0.000150048
 9.94962e-5   1.50496e-5   2.35071e-5      0.000108355  0.000155001
 0.000220705  6.96376e-5   0.000315089     0.000562183  0.000624032
 7.086e-5     5.47539e-5   0.000137396  …  1.74319e-5   0.000257753
 0.00843422   0.00143562   0.00326022      0.00939931   0.0069828  
 0.000713116  8.09506e-5   9.55926e-5      0.000259066  0.000331115
 0.00148565   0.000260937  0.000223807     0.00107824   0.000617886
 0.00281858   0.000307393  0.00257715      0.00480165   0.00219697 
 0.000334445  5.06608e-5   0.000275592  …  0.00108302   0.000175337
 0.000343419  0.000145396  0.000585987     0.000738764  0.00228387 
 0.00293491   0.00264198   0.00325985      0.00296087   0.00467582 
 ⋮                                      ⋱                          
 0.0006459    0.0001957

In [196]:
nearests = """1	[Pair{Any,Any}(("ireland",16),0.64708966f0),Pair{Any,Any}(("britain",16),0.64880353f0),Pair{Any,Any}(("especially",9),0.6513231f0),Pair{Any,Any}(("provided",15),0.67011666f0),Pair{Any,Any}(("particularly",20),0.6725949f0)]
2	[Pair{Any,Any}(("deaths",18),0.6309011f0),Pair{Any,Any}(("sir",20),0.6614016f0),Pair{Any,Any}(("morgan",1),0.6741953f0),Pair{Any,Any}(("west",18),0.6777778f0),Pair{Any,Any}(("isbn",5),0.67834324f0)]
3	[Pair{Any,Any}(("prime",13),0.2473808f0),Pair{Any,Any}(("minister",20),0.31629658f0),Pair{Any,Any}(("prime",1),0.32216263f0),Pair{Any,Any}(("ministers",4),0.34331042f0),Pair{Any,Any}(("minister",3),0.36456484f0)]
4	[Pair{Any,Any}(("list",8),0.59148026f0),Pair{Any,Any}(("and",20),0.614841f0),Pair{Any,Any}(("official",13),0.624194f0),Pair{Any,Any}(("general",18),0.62567335f0),Pair{Any,Any}(("members",15),0.629411f0)]
5	[Pair{Any,Any}(("western",13),0.4191454f0),Pair{Any,Any}(("town",10),0.42082667f0),Pair{Any,Any}(("queensland",4),0.43156624f0),Pair{Any,Any}(("wales",18),0.45057023f0),Pair{Any,Any}(("south",12),0.45707417f0)]
6	[Pair{Any,Any}(("zealand",17),0.51816374f0),Pair{Any,Any}(("match",1),0.51989126f0),Pair{Any,Any}(("us",14),0.5360247f0),Pair{Any,Any}(("test",15),0.5406124f0),Pair{Any,Any}(("first",13),0.5431219f0)]
7	[Pair{Any,Any}(("cartoonist",16),0.647694f0),Pair{Any,Any}(("modernisation",1),0.6486087f0),Pair{Any,Any}(("april",13),0.66997445f0),Pair{Any,Any}(("becoming",20),0.6734446f0),Pair{Any,Any}(("american",8),0.68248886f0)]
8	[Pair{Any,Any}(("matters",20),0.66755116f0),Pair{Any,Any}(("ourselves",1),0.6802366f0),Pair{Any,Any}(("whites",2),0.68125737f0),Pair{Any,Any}(("peace",6),0.68372583f0),Pair{Any,Any}(("more",6),0.68429744f0)]
9	[Pair{Any,Any}(("south",12),0.4463454f0),Pair{Any,Any}(("wales",19),0.4847467f0),Pair{Any,Any}(("new",3),0.5076965f0),Pair{Any,Any}(("zealand",17),0.51473045f0),Pair{Any,Any}(("victoria",11),0.51839817f0)]
10	[Pair{Any,Any}(("aclu",4),0.6944263f0),Pair{Any,Any}(("affects",1),0.69619596f0),Pair{Any,Any}(("requested",17),0.69798505f0),Pair{Any,Any}(("enhanced",19),0.7001114f0),Pair{Any,Any}(("duchy",1),0.70312595f0)]
11	[Pair{Any,Any}(("won",12),0.67440736f0),Pair{Any,Any}(("the",6),0.6763311f0),Pair{Any,Any}(("england",14),0.6785213f0),Pair{Any,Any}(("bishops",13),0.6839303f0),Pair{Any,Any}(("city",7),0.6852726f0)]
12	[Pair{Any,Any}(("eastern",1),0.45826256f0),Pair{Any,Any}(("india",12),0.48450494f0),Pair{Any,Any}(("in",1),0.48777324f0),Pair{Any,Any}(("central",19),0.4917227f0),Pair{Any,Any}(("canada",3),0.49812436f0)]
13	[Pair{Any,Any}(("eight",3),0.6424203f0),Pair{Any,Any}(("b",8),0.66651416f0),Pair{Any,Any}(("nsw",1),0.6762165f0),Pair{Any,Any}(("three",4),0.684096f0),Pair{Any,Any}(("nine",6),0.6855695f0)]
14	[Pair{Any,Any}(("south",17),0.34426063f0),Pair{Any,Any}(("japan",14),0.37043744f0),Pair{Any,Any}(("africa",7),0.3789521f0),Pair{Any,Any}(("and",6),0.38012308f0),Pair{Any,Any}(("east",9),0.3821984f0)]
15	[Pair{Any,Any}(("broke",1),0.6366043f0),Pair{Any,Any}(("july",5),0.6627748f0),Pair{Any,Any}(("zealand",17),0.6700146f0),Pair{Any,Any}(("question",20),0.6760824f0),Pair{Any,Any}(("the",11),0.67849857f0)]
16	[Pair{Any,Any}(("advance",6),0.48215127f0),Pair{Any,Any}(("canada",20),0.5794129f0),Pair{Any,Any}(("britain",20),0.5893681f0),Pair{Any,Any}(("france",9),0.60055745f0),Pair{Any,Any}(("germany",6),0.6300453f0)]
17	[Pair{Any,Any}(("australian",12),0.42347747f0),Pair{Any,Any}(("international",20),0.44074863f0),Pair{Any,Any}(("england",11),0.47114956f0),Pair{Any,Any}(("uk",4),0.47835565f0),Pair{Any,Any}(("an",3),0.47924346f0)]
18	[Pair{Any,Any}(("zealand",12),0.18529892f0),Pair{Any,Any}(("new",3),0.24071127f0),Pair{Any,Any}(("canada",3),0.2889933f0),Pair{Any,Any}(("kingdom",6),0.36203885f0),Pair{Any,Any}(("netherlands",18),0.38124573f0)]
19	[Pair{Any,Any}(("many",8),0.43426085f0),Pair{Any,Any}(("in",15),0.47859168f0),Pair{Any,Any}(("and",20),0.48893946f0),Pair{Any,Any}(("a",11),0.4949652f0),Pair{Any,Any}(("uk",14),0.4982586f0)]
20	[Pair{Any,Any}(("europe",18),0.48324925f0),Pair{Any,Any}(("countries",18),0.49733496f0),Pair{Any,Any}(("canada",15),0.5158184f0),Pair{Any,Any}(("many",1),0.53822476f0),Pair{Any,Any}(("television",7),0.54350066f0)]"""
nearests =[replace(split(entry,"\t")[2],"Pair{Any,Any}","") for entry in split(nearests,"\n")]


20-element Array{String,1}:
 "[((\"ireland\",16),0.64708966f0),((\"britain\",16),0.64880353f0),((\"especially\",9),0.6513231f0),((\"provided\",15),0.67011666f0),((\"particularly\",20),0.6725949f0)]"
 "[((\"deaths\",18),0.6309011f0),((\"sir\",20),0.6614016f0),((\"morgan\",1),0.6741953f0),((\"west\",18),0.6777778f0),((\"isbn\",5),0.67834324f0)]"                        
 "[((\"prime\",13),0.2473808f0),((\"minister\",20),0.31629658f0),((\"prime\",1),0.32216263f0),((\"ministers\",4),0.34331042f0),((\"minister\",3),0.36456484f0)]"          
 "[((\"list\",8),0.59148026f0),((\"and\",20),0.614841f0),((\"official\",13),0.624194f0),((\"general\",18),0.62567335f0),((\"members\",15),0.629411f0)]"                   
 "[((\"western\",13),0.4191454f0),((\"town\",10),0.42082667f0),((\"queensland\",4),0.43156624f0),((\"wales\",18),0.45057023f0),((\"south\",12),0.45707417f0)]"            
 "[((\"zealand\",17),0.51816374f0),((\"match\",1),0.51989126f0),((\"us\",14),0.5360247f0),((\"test\",15),0.5406124f0)

print_clusters (generic function with 1 method)

In [648]:
?groupby

search: groupby num_groups ProcessGroup



No documentation found.

`Iterators.groupby` is a `Function`.

```
# 2 methods for generic function "groupby":
groupby(xs, keyfunc::Function) at /home/ubuntu/.julia/v0.5/Iterators/src/Iterators.jl:518
groupby(keyfunc, xs) at /home/ubuntu/.julia/v0.5/Iterators/src/Iterators.jl:523
```


In [364]:
dist = r
af=affinityprop(dists, display=:final, damp=0.5, maxiter=200)
print_clusters(af)

Affinity propagation converged with 44 iterations: 3 exemplars.
true_examplars = [2,10,11]
true_assignments = [10,2,11,11,10,10,10,10,10,11,10,2,2,10,2,2,2,2,2]
--
*[(("deaths",18),0.6309011f0),(("sir",20),0.6614016f0),(("morgan",1),0.6741953f0),(("west",18),0.6777778f0),(("isbn",5),0.67834324f0)]
[(("eight",3),0.6424203f0),(("b",8),0.66651416f0),(("nsw",1),0.6762165f0),(("three",4),0.684096f0),(("nine",6),0.6855695f0)]
[(("south",17),0.34426063f0),(("japan",14),0.37043744f0),(("africa",7),0.3789521f0),(("and",6),0.38012308f0),(("east",9),0.3821984f0)]
[(("advance",6),0.48215127f0),(("canada",20),0.5794129f0),(("britain",20),0.5893681f0),(("france",9),0.60055745f0),(("germany",6),0.6300453f0)]
[(("australian",12),0.42347747f0),(("international",20),0.44074863f0),(("england",11),0.47114956f0),(("uk",4),0.47835565f0),(("an",3),0.47924346f0)]
[(("zealand",12),0.18529892f0),(("new",3),0.24071127f0),(("canada",3),0.2889933f0),(("kingdom",6),0.36203885f0),(("netherlands",18),0.38124573f0)]
[

In [278]:
function scale_to_range(x, xs, ys)
    scaled_x = x-minimum(xs)/(maximum(xs)-minimum(xs))
    minimum(ys)+scaled_x.*(maximum(ys)-minimum(ys))
end

scale_to_range (generic function with 1 method)

In [301]:
dists

19×19 Array{Float64,2}:
  0.0945462    1.50389   -0.0517176  …  -0.865246   -1.16101   -0.525682 
  1.50389     -0.231096  -0.923457       2.10792     2.28134    2.38486  
 -0.0517176   -0.923457   0.0584093      0.680004    0.339451   0.970045 
 -1.20251      1.66703   -0.226216      -0.0514805  -1.25396   -0.548043 
 -0.558373     2.01014    0.645534      -1.07327     0.196188  -0.31214  
 -0.00866698  -0.340877  -0.512689   …   0.438067    0.743241   0.0395598
 -0.0996641   -0.422912  -0.969897       0.790198    0.137412   0.557045 
  0.827596    -0.883476  -0.83002        0.39127     1.81357    1.55693  
  0.0496075   -0.361393  -0.72681        0.98309     0.55284    0.416044 
  0.887543    -1.4117    -0.967592       1.31207     1.61169    1.3724   
 -1.04526      1.63166    0.635853   …  -0.809929   -0.58368   -0.823253 
  0.373626    -0.876751  -1.25697        1.20308     0.78673    1.58676  
 -1.04307      1.60449    0.13605       -1.14053    -0.657669  -0.428266 
 -0.700976    

In [484]:
odists=pairwise(CorrDist(),rlp,rlp)
dists=(odists-mean(odists))/std(odists)
dists[eye(Bool,size(dists,1))]=(mean(rlp,1)-mean(rlp))/std(rlp)

af=affinityprop(dists, display=:final, damp=0.5, maxiter=200)
print_clusters(af)

Affinity propagation converged with 40 iterations: 2 exemplars.
true_examplars = [2,17]
true_assignments = [2,2,17,2,2,17,17,17,17,17,2,17,2,2,2,17,2,2,2]
--
[(("ireland",16),0.64708966f0),(("britain",16),0.64880353f0),(("especially",9),0.6513231f0),(("provided",15),0.67011666f0),(("particularly",20),0.6725949f0)]
*[(("deaths",18),0.6309011f0),(("sir",20),0.6614016f0),(("morgan",1),0.6741953f0),(("west",18),0.6777778f0),(("isbn",5),0.67834324f0)]
[(("list",8),0.59148026f0),(("and",20),0.614841f0),(("official",13),0.624194f0),(("general",18),0.62567335f0),(("members",15),0.629411f0)]
[(("western",13),0.4191454f0),(("town",10),0.42082667f0),(("queensland",4),0.43156624f0),(("wales",18),0.45057023f0),(("south",12),0.45707417f0)]
[(("eastern",1),0.45826256f0),(("india",12),0.48450494f0),(("in",1),0.48777324f0),(("central",19),0.4917227f0),(("canada",3),0.49812436f0)]
[(("south",17),0.34426063f0),(("japan",14),0.37043744f0),(("africa",7),0.3789521f0),(("and",6),0.38012308f0),(("east",9),0.3

In [485]:
vlp=rlp.-maximum(rlp,2);
dists = pairwise(CorrDist(),vlp,vlp)
scaled_preference = scale_to_range(mean(vlp,1), vlp, dists)
#dists[eye(Bool,size(dists,1))]=scaled_preference
#6*minimum(dists)#+mean(rlp,1)*0.3*(maximum(dists)-minimum(dists))
af=affinityprop(dists, display=:final, damp=0.5, maxiter=200)
print_clusters(af)


Affinity propagation converged with 33 iterations: 2 exemplars.
true_examplars = [5,9]
true_assignments = [9,5,5,9,5,9,9,9,9,5,9,5,9,9,9,9,9,9,9]
--
[(("deaths",18),0.6309011f0),(("sir",20),0.6614016f0),(("morgan",1),0.6741953f0),(("west",18),0.6777778f0),(("isbn",5),0.67834324f0)]
[(("prime",13),0.2473808f0),(("minister",20),0.31629658f0),(("prime",1),0.32216263f0),(("ministers",4),0.34331042f0),(("minister",3),0.36456484f0)]
*[(("western",13),0.4191454f0),(("town",10),0.42082667f0),(("queensland",4),0.43156624f0),(("wales",18),0.45057023f0),(("south",12),0.45707417f0)]
[(("won",12),0.67440736f0),(("the",6),0.6763311f0),(("england",14),0.6785213f0),(("bishops",13),0.6839303f0),(("city",7),0.6852726f0)]
[(("eight",3),0.6424203f0),(("b",8),0.66651416f0),(("nsw",1),0.6762165f0),(("three",4),0.684096f0),(("nine",6),0.6855695f0)]

[(("ireland",16),0.64708966f0),(("britain",16),0.64880353f0),(("especially",9),0.6513231f0),(("provided",15),0.67011666f0),(("particularly",20),0.6725949f0)]
[((

In [486]:
wv = hcat(ee.embedding[word][find(uu.>0)]...)
odists = pairwise(CosineDist(),wv,wv)
dists=(odists-mean(odists))/std(odists)
dists[eye(Bool,size(dists,1))]=(mean(rlp,1)-mean(rlp))/std(rlp)

af=affinityprop(dists, display=:final, damp=0.5, maxiter=200)
print_clusters(af)

Affinity propagation converged with 44 iterations: 3 exemplars.
true_examplars = [2,10,11]
true_assignments = [10,2,11,11,10,10,10,10,10,11,10,2,2,10,2,2,2,2,2]
--
*[(("deaths",18),0.6309011f0),(("sir",20),0.6614016f0),(("morgan",1),0.6741953f0),(("west",18),0.6777778f0),(("isbn",5),0.67834324f0)]
[(("eight",3),0.6424203f0),(("b",8),0.66651416f0),(("nsw",1),0.6762165f0),(("three",4),0.684096f0),(("nine",6),0.6855695f0)]
[(("south",17),0.34426063f0),(("japan",14),0.37043744f0),(("africa",7),0.3789521f0),(("and",6),0.38012308f0),(("east",9),0.3821984f0)]
[(("advance",6),0.48215127f0),(("canada",20),0.5794129f0),(("britain",20),0.5893681f0),(("france",9),0.60055745f0),(("germany",6),0.6300453f0)]
[(("australian",12),0.42347747f0),(("international",20),0.44074863f0),(("england",11),0.47114956f0),(("uk",4),0.47835565f0),(("an",3),0.47924346f0)]
[(("zealand",12),0.18529892f0),(("new",3),0.24071127f0),(("canada",3),0.2889933f0),(("kingdom",6),0.36203885f0),(("netherlands",18),0.38124573f0)]
[

In [ ]:

function kldist(logprobs)
    n_samples, n_models = size(logprobs)
    distence_matrix = Array(Float64,(n_models,n_models))
    for p_i in 1:n_models
        for q_i in 1:n_models
            distence_matrix[p_i,q_i] = corr_dist((logprobs[:,p_i]),(logprobs[:,q_i]))
        end
    end
    distence_matrix
end

In [ ]:
kldist(all_logprobs["a"])

In [ ]:
kldist(all_logprobs["mutual"])

In [ ]:
kldist(all_logprobs["for"])

In [ ]:
all_logprobs["about"]

In [ ]:
all_logprobs["for"]