In [1]:
using DataArrays, DataFrames
using RDatasets


In [ ]:
dataset("Ecdat", "HI") |> |> pz
dataset("Ecdat", "VietNamI")  |> pz

In [2]:
Bwage = dataset("Ecdat", "BudgetUK")

1519x10 DataFrame
| Row  | WFood  | WFuel  | WCloth | WAlc   | WTrans | WOther | TotExp | Income |
|------|--------|--------|--------|--------|--------|--------|--------|--------|
| 1    | 0.4272 | 0.1342 | 0.0    | 0.0106 | 0.1458 | 0.2822 | 50     | 130    |
| 2    | 0.3739 | 0.1686 | 0.0091 | 0.0825 | 0.1215 | 0.2444 | 90     | 150    |
| 3    | 0.1941 | 0.4056 | 0.0012 | 0.0513 | 0.2063 | 0.1415 | 180    | 230    |
| 4    | 0.4438 | 0.1258 | 0.0539 | 0.0397 | 0.0652 | 0.2716 | 80     | 100    |
| 5    | 0.3331 | 0.0824 | 0.0399 | 0.1571 | 0.2403 | 0.1473 | 90     | 100    |
| 6    | 0.3752 | 0.0481 | 0.117  | 0.021  | 0.0955 | 0.3431 | 70     | 70     |
| 7    | 0.2568 | 0.0909 | 0.0453 | 0.0153 | 0.0227 | 0.5689 | 140    | 190    |
| 8    | 0.4533 | 0.2105 | 0.1131 | 0.0161 | 0.0    | 0.207  | 50     | 100    |
| 9    | 0.3279 | 0.1053 | 0.1671 | 0.0293 | 0.0433 | 0.3272 | 100    | 260    |
| 10   | 0.4608 | 0.0612 | 0.023  | 0.0338 | 0.1901 | 0.231  | 90     | 110    |
| 11   | 0.3447 | 0.0392 | 0.2547 | 0.0    | 0.0672 | 0.2942 | 100    | 100    |
⋮
| 1508 | 0.0571 | 0.0454 | 0.0315 | 0.003  | 0.6805 | 0.1824 | 270    | 150    |
| 1509 | 0.4226 | 0.1154 | 0.0089 | 0.1305 | 0.0617 | 0.2609 | 50     | 110    |
| 1510 | 0.4048 | 0.1617 | 0.0402 | 0.0272 | 0.0821 | 0.284  | 60     | 90     |
| 1511 | 0.2544 | 0.0473 | 0.174  | 0.2425 | 0.0963 | 0.1856 | 100    | 130    |
| 1512 | 0.5297 | 0.0554 | 0.0899 | 0.2362 | 0.0335 | 0.0553 | 60     | 90     |
| 1513 | 0.2849 | 0.146  | 0.2391 | 0.1108 | 0.0788 | 0.1404 | 190    | 70     |
| 1514 | 0.6218 | 0.1584 | 0.0    | 0.0    | 0.0    | 0.2197 | 40     | 50     |
| 1515 | 0.4106 | 0.0402 | 0.0054 | 0.07   | 0.2256 | 0.2483 | 90     | 120    |
| 1516 | 0.2787 | 0.1066 | 0.0176 | 0.0    | 0.2196 | 0.3775 | 70     | 90     |
| 1517 | 0.3298 | 0.0759 | 0.2566 | 0.0292 | 0.1309 | 0.1777 | 100    | 260    |
| 1518 | 0.6061 | 0.0459 | 0.0787 | 0.0679 | 0.0259 | 0.1755 | 130    | 160    |
| 1519 | 0.1885 | 0.0328 | 0.1279 | 0.2162 | 0.1575 | 0.2771 | 140    | 140    |

| Row  | Age | Children |
|------|-----|----------|
| 1    | 25  | 2        |
| 2    | 39  | 2        |
| 3    | 47  | 2        |
| 4    | 33  | 2        |
| 5    | 31  | 1        |
| 6    | 24  | 1        |
| 7    | 46  | 1        |
| 8    | 25  | 1        |
| 9    | 30  | 1        |
| 10   | 41  | 1        |
| 11   | 48  | 2        |
⋮
| 1508 | 34  | 1        |
| 1509 | 31  | 1        |
| 1510 | 37  | 2        |
| 1511 | 24  | 1        |
| 1512 | 21  | 1        |
| 1513 | 34  | 2        |
| 1514 | 47  | 1        |
| 1515 | 29  | 2        |
| 1516 | 34  | 2        |
| 1517 | 38  | 2        |
| 1518 | 44  | 2        |
| 1519 | 27  | 1        |

In [3]:
data = Bwage[:,1:6] |> array  |> float
lbls  = Bwage[:,7:end] |> array  |> float

n_train = 0.8*size(data,1) |> int
n_dev  = 0.1*size(data,1) |> int
n_test = 0.1*size(data,1) |> int

data_train = data[1:n_train, :]
data_dev = data[n_train : n_train+n_dev, :]
data_test = data[n_train+n_dev : end, :]

lbls_train = lbls[1:n_train, :]
lbls_dev = lbls[n_train : n_train+n_dev, :]
lbls_test = lbls[n_train+n_dev : end, :]

153x4 Array{Float64,2}:
  70.0  110.0  35.0  2.0
 110.0  160.0  32.0  1.0
  90.0  150.0  37.0  2.0
  90.0  260.0  33.0  1.0
  50.0  120.0  37.0  1.0
  70.0  140.0  36.0  1.0
  40.0  100.0  37.0  1.0
  90.0  100.0  31.0  1.0
  50.0   80.0  27.0  1.0
 150.0  110.0  51.0  1.0
  60.0   90.0  31.0  2.0
 110.0  180.0  37.0  2.0
 130.0  420.0  35.0  1.0
   ⋮                    
 270.0  150.0  34.0  1.0
  50.0  110.0  31.0  1.0
  60.0   90.0  37.0  2.0
 100.0  130.0  24.0  1.0
  60.0   90.0  21.0  1.0
 190.0   70.0  34.0  2.0
  40.0   50.0  47.0  1.0
  90.0  120.0  29.0  2.0
  70.0   90.0  34.0  2.0
 100.0  260.0  38.0  2.0
 130.0  160.0  44.0  2.0
 140.0  140.0  27.0  1.0

In [4]:
macro pz(x)
    x_val = eval(x)
    :( println($(string(x)),"  ",  $x_val|> typeof, "   ", $x_val |> size) )
end

function pz(x)
    println(x|> typeof, "   ", x |> size)
end

pz (generic function with 1 method)

In [19]:
type NN
    W1::Matrix{Float64}
    W2::Matrix{Float64}
        
end

function NN(input_size, hidden_size, output_size)
    W1 = 0.01randn(input_size+1,hidden_size)
    W2 = 0.01randn(hidden_size+1,output_size)
    NN(W1, W2)
end


NN (constructor with 3 methods)

In [125]:
eye(5)[:,1:end-1]

5x4 Array{Float64,2}:
 1.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0
 0.0  0.0  1.0  0.0
 0.0  0.0  0.0  1.0
 0.0  0.0  0.0  0.0

In [207]:
function bias(xs)
    [xs ones(size(xs,1))]
end

function unbias(xs)
    xs[:,1:end-1]
end

function feedforward(nn::NN, xs::Matrix{Float64})
    xs = bias(xs) #add Bias
    as = tanh(xs*nn.W1)
    as = bias(as)
    ŷs = as*nn.W2
    ŷs, as
end

feedforward (generic function with 1 method)

In [268]:
function backprop!(nn::NN, xs::Matrix{Float64}, ys::Matrix{Float64}, α=0.1)
    ŷs, as = feedforward(nn,xs)
    
    ∂e_ŷs = ys - ŷs
    
    ∂ŷ_W2s = as
    ∂ŷ_as = nn.W2
    
    ∂z_W1s = bias(xs)
    
    δW2 = 1/size(xs,1) .* (∂ŷ_W2s'*∂e_ŷs)
    

    ∂e_as =∂e_ŷs * unbias(∂ŷ_as')
    ∂a_zs = 1-unbias(as).^2
  
    δW1 = 1/size(xs,1) .* (∂z_W1s'*(∂a_zs.*∂e_as))
    nn.W2 += α*δW2 
    nn.W1 += α*δW1
    error_rate(ys,ŷs)
end

backprop! (generic function with 2 methods)

In [269]:
nn=NN(size(data,2), 10, size(lbls,2))
backprop!(nn,data_train, lbls_train)

17373.03421086807

In [270]:
[size(nn.W2); size(nn.W1)]

2-element Array{(Int64,Int64),1}:
 (11,4)
 (7,10)

In [271]:
function error_rate(ys::Matrix{Float64}, ŷs::Matrix{Float64})
    es = sum(1/2 * (ŷs-ys).^2,2)
    mean(es)
end

function test(nn::NN, xs::Matrix{Float64}, ys::Matrix{Float64})
    ŷs,_ = feedforward(nn,xs)
    error_rate(ys,ŷs)
end

test (generic function with 1 method)

In [297]:
function early_stopping!(nn::NN, 
                        xs::Matrix{Float64}, ys::Matrix{Float64},
                        xs_dev::Matrix{Float64}, ys_dev::Matrix{Float64},
    max_epochs=5, max_patience=Inf)
    er_dev_best = Inf
    nn_best = nn
    patience=max_patience
    for epoch_number in 1: max_epochs
        er_train = backprop!(nn,xs,ys,0.001)
        er_dev = test(nn, xs_dev, ys_dev)
        
        if er_dev>er_dev_best
            patience-=1
        else
            print("!")
            patience=max_patience
            nn_best = deepcopy(nn)
            er_dev_best=er_dev
        end
        
        println("Err Train: $er_train, Err Dev: $er_dev")
        if patience<=0
            break
        end
    end
    
    nn.W1 = nn_best.W1 #Overwrite with best value
    nn.W2 = nn_best.W2 #Overwrite with best value
    
    
end

early_stopping! (generic function with 3 methods)

In [ ]:
nn=NN(size(data,2), 25, size(lbls,2))
early_stopping!(nn,data_train, lbls_train, data_dev, lbls_dev, 10000000, 100)

!Err Train: 17374.0553411008, Err Dev: 18120.226725965127
!Err Train: 17344.806675667798, Err Dev: 18089.97000634087
!Err Train: 17315.58988965346, Err Dev: 18059.71924412996
!Err Train: 17286.380232012518, Err Dev: 18029.443283824334
!Err Train: 17257.147718603836, Err Dev: 17999.10163625063
!Err Train: 17227.85338814345, Err Dev: 17968.63963052857
!Err Train: 17198.444635250395, Err Dev: 17937.982042412164
!Err Train: 17168.849077232444, Err Dev: 17907.024502052103
!Err Train: 17138.966283633705, Err Dev: 17875.62179674189
!Err Train: 17108.656517084277, Err Dev: 17843.571948515928
!Err Train: 17077.725407030677, Err Dev: 17810.594685743523
!Err Train: 17045.90322676487, Err Dev: 17776.302701138466
!Err Train: 17012.81722556517, Err Dev: 17740.164021832203
!Err Train: 16977.955402886026, Err Dev: 17701.4541460241
!Err Train: 16940.620427245558, Err Dev: 17659.197711150282
!Err Train: 16899.873470513714, Err Dev: 17612.10187607215
!Err Train: 16854.470055616526, Err Dev: 17558.4878188

In [299]:
test(nn, data_test, lbls_test)

2432.689147469655

In [300]:
xs = data_test[1:2,:]

feedforward(nn,xs)

(
2x4 Array{Float64,2}:
  79.2696  126.359  36.05    1.64725
 115.099   145.014  35.5715  1.59966,

2x26 Array{Float64,2}:
 0.993601  0.992426  0.269651  -0.277035  …  -0.993635  -0.988872  1.0
 0.993787  0.992793  0.637276  -0.851326     -0.993796  -0.990105  1.0)

In [301]:
ys = lbls_test[1:2,:]



2x4 Array{Float64,2}:
  70.0  110.0  35.0  2.0
 110.0  160.0  32.0  1.0

In [28]:
lbl_train |> pz
data_train |> pz

LoadError: lbl_train not defined
while loading In[28], in expression starting on line 1

In [354]:
help(copy!)

INFO: Loading help data...


Base.copy!(dest, src)

   Copy all elements from collection "src" to array "dest".
   Returns "dest".

Base.copy!(dest, do, src, so, N)

   Copy "N" elements from collection "src" starting at offset
   "so", to array "dest" starting at offset "do". Returns
   "dest".
