In [1]:
addprocs(10)
using AdaGram

  likely near /home/ubuntu/.julia/v0.5/AdaGram/src/AdaGram.jl:49
  likely near /home/ubuntu/.julia/v0.5/AdaGram/src/AdaGram.jl:49
  likely near /home/ubuntu/.julia/v0.5/AdaGram/src/AdaGram.jl:49
  likely near /home/ubuntu/.julia/v0.5/AdaGram/src/AdaGram.jl:49
  likely near /home/ubuntu/.julia/v0.5/AdaGram/src/AdaGram.jl:49
  likely near /home/ubuntu/.julia/v0.5/AdaGram/src/AdaGram.jl:49
  likely near /home/ubuntu/.julia/v0.5/AdaGram/src/AdaGram.jl:49
  likely near /home/ubuntu/.julia/v0.5/AdaGram/src/AdaGram.jl:49
  likely near /home/ubuntu/.julia/v0.5/AdaGram/src/AdaGram.jl:49
  likely near /home/ubuntu/.julia/v0.5/AdaGram/src/AdaGram.jl:49
  likely near /home/ubuntu/.julia/v0.5/AdaGram/src/AdaGram.jl:49
  likely near /home/ubuntu/.julia/v0.5/AdaGram/src/AdaGram.jl:49
  likely near /home/ubuntu/.julia/v0.5/AdaGram/src/AdaGram.jl:49
  likely near /home/ubuntu/.julia/v0.5/AdaGram/src/AdaGram.jl:49
  likely near /home/ubuntu/.julia/v0.5/AdaGram/src/AdaGram.jl:49
  likely near /home/ubunt

In [33]:
train_fn  =  "../../eval/data/corpora/WikiCorp/tokenised_lowercase_WestburyLab.wikicorp.201004.txt" #"training text data"
output_fn = "../../eval/models/adagram/v1_d100.adagram_model"#"file to save the model (in Julia format)"
dict_fn = "../../eval/data/corpora/WikiCorp/tokenised_lowercase_WestburyLab.wikicorp.201004.1gram" #"dictionary file with word frequencies"

window = 4 #"(max) window size"
min_freq  = 20 #"min. frequency of the word"
remove_top_k = 0 #"remove top K most frequent words"
dim  = 100 #"dimensionality of representations"
prototypes = 5 #"number of word prototypes"
alpha = 0.1 #"prior probability of allocating a new prototype"
d  = 0.0 #"parameter of Pitman-Yor process"
subsample = 1e-5 #"subsampling treshold. useful value is 1e-5"
context_cut  = true #"randomly reduce size of the context"
epochs = 1 #"number of epochs to train"
initcount = 1. #"initial weight (count) on first sense for each word"
stopwords =Set{AbstractString}() #"list of stop words"
sense_treshold = 1e-10 #"minimal probability of a meaning to contribute into gradients"
save_treshold = 1e-3 #"minimal probability of a meaning to save after training"
regex = r"" #"ignore words not matching provided regex"


r""

In [3]:
print("Building dictionary... ")
vm, dict = read_from_file(dict_fn, dim, prototypes, min_freq,remove_top_k, stopwords; regex=regex)
println("Done!")


Building dictionary... Done!


In [4]:
vm.alpha = alpha
vm.d = d

0.0

In [ ]:
inplace_train_vectors!(vm, dict, train_fn, window;
                       threshold=subsample, context_cut=context_cut,
                       epochs=epochs, init_count=initcount, sense_treshold=sense_treshold)



 in depwarn(::String, ::Symbol) at ./deprecated.jl:64
 in remotecall(::Int64, ::Function, ::Int64, ::Vararg{Int64,N}) at ./deprecated.jl:50
 in #inplace_train_vectors!#18(::Int64, ::Float64, ::Void, ::Float64, ::Bool, ::Int64, ::Float64, ::Float64, ::AdaGram.#inplace_train_vectors!, ::AdaGram.VectorModel, ::AdaGram.Dictionary, ::String, ::Int64) at /home/ubuntu/.julia/v0.5/AdaGram/src/gradient.jl:154
 in (::AdaGram.#kw##inplace_train_vectors!)(::Array{Any,1}, ::AdaGram.#inplace_train_vectors!, ::AdaGram.VectorModel, ::AdaGram.Dictionary, ::String, ::Int64) at ./<missing>:0
 in include_string(::String, ::String) at ./loading.jl:380
 in execute_request_0x535c5df2(::ZMQ.Socket, ::IJulia.Msg) at /home/ubuntu/.julia/v0.5/IJulia/src/execute_request.jl:183
 in eventloop(::ZMQ.Socket) at /home/ubuntu/.julia/v0.5/IJulia/src/IJulia.jl:143
 in (::IJulia.##26#32)() at ./task.jl:309
while loading In[5], in expression starting on line 1


	From worker 2:	64000 words read, 1296374/596129680
	From worker 2:	0.02% -11.1842 0.0250 0.0250 2.14/3.00 3.13 kwords/sec
	From worker 2:	0.02% -11.1178 0.0250 0.0250 2.00/3.00 3.84 kwords/sec
	From worker 2:	0.02% -11.1022 0.0250 0.0250 1.91/3.00 3.90 kwords/sec
	From worker 2:	0.02% -11.0636 0.0250 0.0250 1.84/3.00 3.92 kwords/sec
	From worker 3:	64000 words read, 597414099/1192259360
	From worker 2:	0.03% -11.0132 0.0250 0.0250 1.78/3.00 3.91 kwords/sec


In [34]:

save_model(output_fn, vm, dict, save_treshold)

In [49]:
word = "apple"
prior_probs = expected_pi(vm, dict.word2id[word])
for ii in 1:5
    println(prior_probs[ii],"\t",nearest_neighbors(vm, dict, word, ii, 10))
    println()
end

0.06530734158491676	Tuple{AbstractString,Int64,Float32}[("united",2,0.983088),("county",3,0.90978),("statistical",2,0.900458),("cdp",2,0.897619),("census",1,0.891764),("township",3,0.890909),("metropolitan",1,0.887711),("bureau",1,0.877118),("2000",2,0.875254),("minnesota",1,0.874623)]

0.9346925294866518	Tuple{AbstractString,Int64,Float32}[("united",1,0.896622),("u.s",1,0.827811),("jackson-vanik",1,0.7056),("jones-shafroth",1,0.683918),("states—the",1,0.683617),("sates",1,0.682901),("rechartering",1,0.662349),("commonwealth’s",1,0.66137),("risenhoover",1,0.660591),("9981",1,0.657262)]

1.1720787006966776e-7	Tuple{AbstractString,Int64,Float32}[("orient",1,0.344258),("weymouth",1,0.339116),("rmi",1,0.338006),("rocs",1,0.335061),("barrow-in-furness",1,0.331527),("yachts",1,0.326889),("rc",1,0.319309),("hamworthy",1,0.317995),("faw",1,0.316552),("extend",1,0.314892)]

1.0655055733396529e-8	Tuple{AbstractString,Int64,Float32}[("trial",1,0.395745),("extradition",1,0.387345),("six-month",1,0

In [59]:
?names

search: names fieldnames dirname tempname fullname basename TypeName fieldname



```
names(x::Module[, all=false[, imported=false]])
```

Get an array of the names exported by a `Module`, with optionally more `Module` globals according to the additional parameters.


In [149]:
blk = quote
    const train_fn  =  "../../eval/data/corpora/WikiCorp/tokenised_lowercase_WestburyLab.wikicorp.201004.txt" #"training text data"
output_fn = "../../eval/models/adagram/v1_d100.adagram_model"#"file to save the model (in Julia format)"
dict_fn = "../../eval/data/corpora/WikiCorp/tokenised_lowercase_WestburyLab.wikicorp.201004.1gram" #"dictionary file with word frequencies"

window = 4 #"(max) window size"
min_freq  = 20 #"min. frequency of the word"
remove_top_k = 0 #"remove top K most frequent words"
dim  = 100 #"dimensionality of representations"
prototypes = 5 #"number of word prototypes"
alpha = 0.1 #"prior probability of allocating a new prototype"
d  = 0.0 #"parameter of Pitman-Yor process"
subsample = 1e-5 #"subsampling treshold. useful value is 1e-5"
context_cut  = true #"randomly reduce size of the context"
epochs = 1 #"number of epochs to train"
initcount = 1. #"initial weight (count) on first sense for each word"
stopwords =Set{AbstractString}() #"list of stop words"
sense_treshold = 1e-10 #"minimal probability of a meaning to contribute into gradients"
save_treshold = 1e-3 #"minimal probability of a meaning to save after training"
#regex = r"" #"ignore words not matching provided regex"
    end |> dump

Expr
  head: Symbol block
  args: Array{Any}((34,))
    1: Expr
      head: Symbol line
      args: Array{Any}((2,))
        1: Int64 2
        2: Symbol In[149]
      typ: Any
    2: Expr
      head: Symbol const
      args: Array{Any}((1,))
        1: Expr
          head: Symbol =
          args: Array{Any}((2,))
            1: Symbol train_fn
            2: String "../../eval/data/corpora/WikiCorp/tokenised_lowercase_WestburyLab.wikicorp.201004.txt"
          typ: Any
      typ: Any
    3: Expr
      head: Symbol line
      args: Array{Any}((2,))
        1: Int64 3
        2: Symbol In[149]
      typ: Any
    4: Expr
      head: Symbol =
      args: Array{Any}((2,))
        1: Symbol output_fn
        2: String "../../eval/models/adagram/v1_d100.adagram_model"
      typ: Any
    5: Expr
      head: Symbol line
      args: Array{Any}((2,))
        1: Int64 4
        2: Symbol In[149]
      typ: Any
    ...
    30: Expr
      head: Symbol =
      args: Array{Any}((2,))
        1: Symb

In [65]:
names(current_module())

36-element Array{Symbol,1}:
 :AdaGram       
 :ArrayViews    
 :Base          
 :Compat        
 :Core          
 :Devectorize   
 :IJulia        
 :IPythonDisplay
 :JSON          
 :Main          
 :Nettle        
 :ZMQ           
 :add_to_path   
 :alpha         
 :blk           
 :context_cut   
 :d             
 :dict          
 :dict_fn       
 :dim           
 :epochs        
 :initcount     
 :min_freq      
 :output_fn     
 :prior_probs   
 :prototypes    
 :regex         
 :remove_top_k  
 :save_treshold 
 :sense_treshold
 :stopwords     
 :subsample     
 :train_fn      
 :vm            
 :window        
 :word          

In [154]:
?append!

search: append! apply_gradient!



```
append!(collection, collection2) -> collection.
```

Add the elements of `collection2` to the end of `collection`.

```jldoctest
julia> append!([1],[2,3])
3-element Array{Int64,1}:
 1
 2
 3
```

```jldoctest
julia> append!([1, 2, 3], [4, 5, 6])
6-element Array{Int64,1}:
 1
 2
 3
 4
 5
 6
```

Use [`push!`](:func:`push!`) to add individual items to `collection` which are not already themselves in another collection. The result is of the preceding example is equivalent to `push!([1, 2, 3], 4, 5, 6)`.


In [205]:
function names_candidates(blk::Expr)
    names_in_block = Vector{Symbol}()
    for a in blk.args
        typeof(a) <: Expr || continue
        if a.head == :(=)
            push!(names_in_block, a.args[1])
        else #Recurse, so we captured things in blocks or behind `const`
            append!(names_in_block, names_candidates(a))
        end
    end
    names_in_block
end

macro param_save(filename, blk::Expr)
    names_in_block =  names_candidates(blk)    
    quote
        $(esc(blk))
        names_defined = Set($(names_in_block)) #∩ Set(names(current_module()))
        names_and_vals =[(string(name), eval(name)) for name in names_defined]
        JLD.save($filename, Base.flatten(names_and_vals)...)
        println("Paramaters -- saved to $($filename)")
        println("----------")
        println(join(("$n = $v" for (n,v) in names_and_vals),"\n"))
        println("----------")
    end
end

@param_save (macro with 1 method)

In [207]:
;rm "../../eval/models/adagram/v1_d100_2.params.jld" 

In [206]:
#macroexpand(quote
@param_save  "../../eval/models/adagram/v1_d100_2.params.jld" begin
    train_fn  =  "../../eval/data/corpora/WikiCorp/tokenised_lowercase_WestburyLab.wikicorp.201004.txt" #"training text data"
    output_fn = "../../eval/models/adagram/v1_d100.adagram_model"#"file to save the model (in Julia format)"
    dict_fn = "../../eval/data/corpora/WikiCorp/tokenised_lowercase_WestburyLab.wikicorp.201004.1gram" #"dictionary file with word frequencies"

    const wixndow = 4 #"(max) window size"
    min_freq  = 20 #"min. frequency of the word"
    remove_top_k = 0 #"remove top K most frequent words"
    dim  = 100 #"dimensionality of representations"
    prototypes = 5 #"number of word prototypes"
    alpha = 0.1 #"prior probability of allocating a new prototype"
    d  = 0.0 #"parameter of Pitman-Yor process"
    subsample = 1e-5 #"subsampling treshold. useful value is 1e-5"
    context_cut  = true #"randomly reduce size of the context"
    epochs = 1 #"number of epochs to train"
    initcount = 1. #"initial weight (count) on first sense for each word"
    stopwords =Set{AbstractString}() #"list of stop words"
    sense_treshold = 1e-10 #"minimal probability of a meaning to contribute into gradients"
    save_treshold = 6 #"minimal probability of a meaning to save after training"
end
#end)

Paramaters -- saved to ../../eval/models/adagram/v1_d100_2.params.jld
----------
train_fn = ../../eval/data/corpora/WikiCorp/tokenised_lowercase_WestburyLab.wikicorp.201004.txt
alpha = 0.1
subsample = 1.0e-5
sense_treshold = 1.0e-10
initcount = 1.0
epochs = 1
output_fn = ../../eval/models/adagram/v1_d100.adagram_model
min_freq = 20
prototypes = 5
context_cut = true
stopwords = Set{AbstractString}()
remove_top_k = 0
save_treshold = 6
wixndow = 4
dict_fn = ../../eval/data/corpora/WikiCorp/tokenised_lowercase_WestburyLab.wikicorp.201004.1gram
dim = 100
d = 0.0
----------


In [166]:
JLD.load("../../eval/models/adagram/v1_d100_2.params.jld")

Dict{String,Any} with 1 entry:
  "save_treshold" => 6

In [51]:
 println("Using ", nprocs(), " processors")

Using 11 processors
