In [63]:
using Iterators
using Pipe
using Compat

macro printval(ee)
    ee_expr = @sprintf "%s" string(ee)
    esc(:(println($ee_expr," = ", $ee)))
end

macro pz(ee)
    ee_expr = @sprintf "%s" string(ee)
    esc(:(println($ee_expr,"\t\t",typeof($ee), "\t", size($ee))))
end

push!(LOAD_PATH, ".")
push!(LOAD_PATH, "../util/")

6-element Array{ByteString,1}:
 "/home/ubuntu/build/julia-master/usr/local/share/julia/site/v0.5"
 "/home/ubuntu/build/julia-master/usr/share/julia/site/v0.5"      
 "."                                                              
 "../util/"                                                       
 "."                                                              
 "../util/"                                                       

In [ ]:
addprocs(11)

In [ ]:
@everywhere using Distances

In [ ]:

@everywhere data = open("doctors_letters.jsz","r") do fh
    deserialize(fh)    
end
test_set = data["test_set"];
data

In [ ]:

@everywhere data = open("atis_data2.jsz","r") do fh
    deserialize(fh)    
end
test_set = data["test_set"];
data

In [ ]:

@everywhere data = open("brown_data.jsz","r") do fh
    deserialize(fh)    
end
test_set = data["test_set"];
data

In [ ]:
@everywhere function lookup_sowe(data, sent::AbstractString)
    lookup_sowe(data, sent |> split)
end

@everywhere function lookup_sowe{S<:AbstractString}(data, sent::Vector{S})
    sum([data["LL"][:,data["word_indexes"][word]] for word in sent]) 
end

@everywhere function lookup_words(data, path)
    [data["indexed_words"][ii] for ii in path]
end

In [ ]:
@everywhere const ϵ = 10.0^-6

In [209]:
@everywhere @inline function get_end(LL, ws::Vector{Int64})
    @inbounds sofar = length(ws)>0 ? sum([LL[:,ii] for ii in ws]) : zeros(LL[:,1])
    sofar
end

@everywhere function score_possible_additions(LL, target, end_point)
    -pairwise(Euclidean(), LL, (target-end_point)'');
end   

@everywhere  @inline function fitness(target, end_point)
    #Fitter is larger
    -euclidean(end_point, target)   
end

@everywhere function greedy_addition(LL::Matrix{Float64},
                         target::Vector{Float64},
                         best_word_set::Vector{Int},
                         max_additions = Inf)
    end_point = get_end(LL, best_word_set)
    best_score = fitness(target, end_point)
    
    did_improve = true
    cur_additions = 0
    while(did_improve && cur_additions<max_additions)
        cur_additions+=1
        did_improve=false
        
        addition_scores = score_possible_additions(LL, target, end_point)
        addition_score, addition = findmax(addition_scores)
        if addition_score>best_score+ϵ
            #println("!add: $addition $best_score")
            best_score=addition_score
            best_word_set = [best_word_set...,addition]
            end_point += LL[:,addition]
            did_improve=true
        end
    end
    best_word_set,best_score
end


@everywhere function word_swap_refinement(LL::Matrix{Float64},
                              target::Vector{Float64},
                              best_word_set::Vector{Int}, 
                              max_swaps=1)
    
    initial_word_set = copy(best_word_set)
    end_point = get_end(LL, best_word_set)
    best_score = fitness(target, end_point)
    
    function update_best!(word_set,score)
        if score>best_score+ϵ #scores are negative
            best_score=score
            best_word_set = word_set
            #println("*swap, new set: $word_set $score")
        end
    end

    for ii in 1:length(initial_word_set)
        word_set = initial_word_set[[1:ii-1; ii+1:end]]
        sub_endpoint = end_point - LL[:,ii]
        subset_score = fitness(LL, target, sub_endpoint)
        update_best!(word_set, subset_score)

        add_word_set, add_score = greedy_addition(LL, target, word_set, 1) #Try adding just one greedily
        update_best!(add_word_set, add_score)
    end

    best_word_set,best_score
        
end



@everywhere function greedy_search{S<:AbstractString}(data::Dict, target_sent::Vector{S}, max_swaps=1, rounds=3; log=false)
    target::Vector{Float64} = lookup_sowe(data,target_sent)
    greedy_search(data, target, max_swaps, rounds, log=log)
        
end

@everywhere function greedy_search(data::Dict, target::Vector{Float64}, max_swaps=1, rounds=3; log=false)
    get_words(word_iis) = [data["indexed_words"][ii] for ii in word_iis]
    
    word_iis = Int[]
    score=-Inf
    for round in 1:rounds
        word_iis, add_score = greedy_addition(data["LL"], target, word_iis)
        log && println("POST_ADD_STEP: $add_score $(get_words(word_iis))")
        
       
        word_iis, swap_score = word_swap_refinement(data["LL"], target, word_iis, max_swaps)
        
        log && println("POST_SWAP_STEP: $swap_score $(get_words(word_iis))")
        
        if swap_score==score break end
        
        score=swap_score
    end
    get_words(word_iis),score,word_iis
        
end

In [185]:
LL = data["LL"]
len_LL2 = (size(LL,2).^2  + size(LL,2))÷ 2
LL2_index = Matrix{Int}(len_LL2, 2)
LL2 = Matrix{Float64}(size(LL,1), len_LL2)  .*0 .-1
kk=0
for ii in 1:size(LL,2)
    for jj in 1:ii
        kk+=1
        LL2_index[kk,:] = [ii,jj]
        LL2[:,kk] = LL[:,ii]+LL[:,jj]
    end
end

In [215]:
function double_word_swap_refinement(LL::Matrix{Float64},
                              LL2::Matrix{Float64}, LL2_index,
                              target::Vector{Float64},
                              best_word_set::Vector{Int})
    
    initial_word_set = copy(best_word_set)
    initial_end_point = get_end(LL, initial_word_set)
    best_score = fitness(LL, target, best_word_set)
    
    for ii in 1:length(initial_word_set)
        for jj in ii+1:length(initial_word_set)
            end_point = initial_end_point - LL[:,initial_word_set[ii]] - LL[:,initial_word_set[jj]]
            addition_score, addition_index = findmax(score_possible_additions(LL2, target, end_point))
            if addition_score>best_score + ϵ
                #println("+= $(LL2_index[addition_index,:])")
                
                word_subset = initial_word_set[[1:ii-1; ii+1:jj-1; jj+1:end]]
                best_word_set = [word_subset..., LL2_index[addition_index,:]...]
                best_score = addition_score
            end
        end
    end

    best_word_set,best_score
        
end

#double_word_swap_refinement(LL, LL2, LL2_index, LL2[:,4], [1,2,3,4,5])

double_word_swap_refinement (generic function with 3 methods)

In [213]:
target_sent = test_set[664]
println(target_sent)
println("-------------")
best_words, best_score, best_wordset  = greedy_search(data, target_sent, 1,100, log=true)


SubString{ASCIIString}["where","does","this","flight","make","a","stop"]
-------------
POST_ADD_STEP: -5.491303831565617 Any["you","a","not","flight","this","stop","where"]


(Any["a","not","flight","this","stop","where","makes"],-3.477294814142913,[6,26,471,27,367,82,388])

POST_SWAP_STEP: -3.4772948141429105 Any["a","not","flight","this","stop","where","makes"]
POST_ADD_STEP: -3.477294814142913 Any["a","not","flight","this","stop","where","makes"]
POST_SWAP_STEP: -3.477294814142913 Any["a","not","flight","this","stop","where","makes"]
POST_ADD_STEP: -3.477294814142913 Any["a","not","flight","this","stop","where","makes"]
POST_SWAP_STEP: -3.477294814142913 Any["a","not","flight","this","stop","where","makes"]


In [218]:
target_sowe = lookup_sowe(data,target_sent)
new_best_words, new_best_score =double_word_swap_refinement(LL, LL2, LL2_index, target_sowe, best_wordset)
[[data["word_indexes"][ii] for ii in target_sent]>sort  new_best_words|>sort]

+= [178 118]


LoadError: LoadError: MethodError: `isless` has no method matching isless(::Function, ::Array{Any,1})
while loading In[218], in expression starting on line 3

In [208]:
score_possible_additions(LL2,target_sowe, [6,471,27,367,82])[15871]

LoadError: LoadError: DimensionMismatch("dimensions must match")
while loading In[208], in expression starting on line 1

In [193]:
fitness(LL, target_sowe, [[178, 118]..., [6,471,27,367,82]...])

-0.0

In [190]:
find((LL2_index[:,2] .==118) & (LL2_index[:,1] .== 178))

1-element Array{Int64,1}:
 15871

In [191]:
LL2[:,15871]

300-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 ⋮  
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

7-element Array{Any,1}:
  82
 178
  27
 471
 118
   6
 367

In [176]:
1

1

[471,27,367,82,388]
[26,27,367,82,388]
[26,471,367,82,388]
[26,471,27,82,388]
[26,471,27,367,388]
[26,471,27,367,82]
[6,27,367,82,388]
[6,471,367,82,388]
[6,471,27,82,388]
[6,471,27,367,388]
[6,471,27,367,82]
[6,26,367,82,388]
[6,26,27,82,388]
[6,26,27,367,388]
[6,26,27,367,82]
[6,26,471,82,388]
[6,26,471,367,388]
[6,26,471,367,82]
[6,26,471,27,388]
[6,26,471,27,82]
[

7x2 Array{Any,2}:
 "a"       "a"     
 "does"    "flight"
 "flight"  "makes" 
 "make"    "not"   
 "stop"    "stop"  
 "this"    "this"  
 "where"   "where" 

6,26,471,27,367]


In [122]:
ii=664
#while true
    #ii=rand(1:1000)
    target_sent = test_set[ii]
    println(join(target_sent, " "))
    println("-----------------------------")

    _, score = greedy_search(data, target_sent, 1,100, log=true)
    if score<0
        break
    end
#end

where does this flight make a stop


LoadError: LoadError: syntax: unexpected ,
while loading In[122], in expression starting on line 8

-----------------------------


POST_ADD_STEP: -5.491303831565617 Any["you","a","not","flight","this","stop","where"]


(Any["a","not","flight","this","stop","where","makes"],-3.477294814142913,[6,26,471,27,367,82,388])

POST_SWAP_STEP: -3.4772948141429105 Any["a","not","flight","this","stop","where","makes"]
POST_ADD_STEP: -3.477294814142913 Any["a","not","flight","this","stop","where","makes"]
POST_SWAP_STEP: -3.477294814142913 Any["a","not","flight","this","stop","where","makes"]
POST_ADD_STEP: -3.477294814142913 Any["a","not","flight","this","stop","where","makes"]
POST_SWAP_STEP: -3.477294814142913 Any["a","not","flight","this","stop","where","makes"]


In [181]:
1

1

7x2 Array{Any,2}:
 "a"       "a"     
 "does"    "flight"
 "flight"  "makes" 
 "make"    "not"   
 "stop"    "stop"  
 "this"    "this"  
 "where"   "where" 

In [ ]:
res = pmap([1:length(test_set);], test_set) do ii,target_sent
    sol, score = greedy_search(data, target_sent, 1, 100, log=false)
    (sol, score, ii)
end

In [ ]:
open("atis2_res_glove.jsz","w") do fh
    serialize(fh, (Vector{ASCIIString}[sol for (sol, score, ii) in res], test_set)
    )    
end



In [ ]:
se = lookup_sowe(atis_data, ["flights","serve","lunch","which"])
se=se*0.6
greedy_search(atis_data, se, 1, 5, log=false)

In [ ]:
hard_cases = find(x->x[2]<0, res)
res[hard_cases]

In [ ]:
test_set[hard_cases]

In [ ]:
hard_set =  test_set[hard_cases]

hard_res = pmap([1:length(hard_set);], hard_set) do ii,target_sent
    sol, score = greedy_search(atis_data, target_sent, 2,5, log=false)
    (sol, score, ii)
end

In [ ]:
very_hard_cases = find(x->x[2]<0.0, hard_res)

In [ ]:
factorial(14)

In [ ]:
hard_res[very_hard_cases]

In [ ]:


for (ii,target_sent) in enumerate(test_set)
    sol, score = greedy_search(atis_data, target_sent, log=false)
    if score>0
        print("$ii - ")
        println(join(target_sent, " "))
    end
end
    

In [ ]:
enumerate(test_set) |> collect

In [ ]:
# τ = Pheromone
# η = Prior
# α = pheremone weight
# β = prior weight
# ρ = pheremone evaporation

@everywhere @inline function select_index{V<:AbstractVector}(edge_probs::V)
    cutoff = rand()
    total = 0.0
    @assert(length(edge_probs)>0, "No probs given")
    for (ii,prob) in enumerate(edge_probs)
        total+=prob
        if total>=cutoff
            return ii
        end
    end
    
    @assert(total>=cutoff, "total= $total, cutoff=$cutoff, $edge_probs") #Should Never Reach this point
end


@everywhere function evaporate!{M<:AbstractArray}(τ::M, ρ)
    τ.*=(1.0-ρ) #Evaporation
end

    

@everywhere function deposit!{M<:AbstractVector}(τ::M, path, fit)
    #Are You In or Out?  Double Crosser or Devout
    #Order actually means nothing in this problem
    #Cooccurance doesn't really many anything either
    #Cooccurance is a problem for the prior that need 
    #to be conerned with all answers not just this one
    for node in path
        @inbounds τ[node] += fit./length(path)
    end
    τ
end

@everywhere function get_edge_probs(τ,η::Function, α, β)
    τ_scaled = (τ).^α
    function get_prob(state)
        η_scaled = (η(state)).^β
        tot = τ_scaled .* τ_scaled
        tot./sum(tot)
    end
end

@everywhere @inline function select_node(edge_probs::Function, path=[])
    select_index(edge_probs(path))
end


In [ ]:
#If you pass in a start index of greater than zero, then atre using a starting index, otherswise not
@everywhere function run_ant(edge_probs, end_prob_dist)
    path = Int[]
    len = select_index(end_prob_dist)
    for _ in 1:len
        push!(path, select_node(edge_probs, path))
    end
    path    
end


function optimise(fit_fun, τ, η, end_prob_dist;  α=1, β=1,ρ=0, n_ants=100, n_gens=10, callback=Union{})
    assert(α>=1.0)
    assert(β>=1.0)
    assert(0.0<=ρ<1.0)
    
    max_fit::Float64 = -Inf;
    fittest_path::Vector{Int} = []
    
    for gen_ii in 1:n_gens

        edge_probs = get_edge_probs(τ,η, α, β)

        path_fits::Vector{Tuple{Vector{Int},Float64}} = map(1:n_ants) do ant_id
            path::Vector{Int} = run_ant(edge_probs, end_prob_dist)
            fit::Float64 = fit_fun(path)
            (path, fit)
        end
        
        ranked_path_fits = select!(path_fits,1:100, by=pf->-pf[2])
        scales = 100:-1:1
        
        evaporate!(τ,ρ)
        for ((path, fit),scale) in zip(ranked_path_fits,scales)
        #for (path, fit) in path_fits
            if fit>max_fit
                max_fit = fit
                fittest_path = path
                
                if fit==Inf #Perfect Fit
                    return fittest_path, max_fit
                end
            end
            deposit!(τ,path, fit)
        end
        
        if callback |> typeof <:Function
            callback(gen_ii, τ,fittest_path,max_fit,path_fits)
        end
        
    end #Next Generation
    
    fittest_path, max_fit, τ
end


function optimise(fit_fun, n_dims::Int64, η::Function, end_prob_dist; kwargs...)
    τ = [rand() for nn in 1:n_dims]
    
    optimise(fit_fun, τ, η, end_prob_dist;kwargs...)
end


In [ ]:
@fastmath function get_prior_fun(uni_occur,bi_occur)
    n_edges=length(uni_occur)
    function prior(ws)
        if length(ws)==0
            uni_occur
        elseif length(ws)==1
            bi_occur[:,ws[1]]
        else
            (uni_occur + sum([bi_occur[:,w] for w in ws]))/(length(ws)+1) #Just average them cos its cheap
        end
    end    
end




In [ ]:
function built_optimise(data::Dict, target_sent::AbstractString, log=False; kwargs...)
    target::Vector{Float64} = lookup_sowe(data,target_sent)
    LL =data["LL"]
    indexed_words=data["indexed_words"]
    @inline function fitness(path)
        #Fitter is larger
        @inbounds path_end = sum([LL[:,ii] for ii in path]) 
        -1.0*euclidean(path_end, target)
    end

    τlog=[]
    if log
        log = (gen_ii, τ,fittest_path,max_fit, path_fits) -> begin
            print("oGen: $gen_ii - fit: $max_fit ")
            print(lookup_words(data, fittest_path))
            #path_lens = [length(pf[1]) for pf in path_fits]
            #print("mean_len = $(mean(path_lens))")
            #print(" max_len = $(maximum(path_lens))")
            println()
            push!(τlog,copy(τ))
            
        end
    end
    
    n_dims = size(LL,2)
    length_dist = data["length_prob"]
    #length_dist = ws->0.5
    prior = get_prior_fun(data["unioccur"], data["bioccur"])
       
    
    
    path, score, τ = optimise(fitness,n_dims, prior, length_dist; callback=log, kwargs...)
    push!(τlog,τ)
    score,lookup_words(data, path), τlog
end

In [ ]:
@time score, words, τlog = built_optimise(atis_data,"show flights from washington to san francisco", true;
α=1, β=1, ρ=0.2, n_ants=10000, n_gens=10);
words

In [ ]:
greedy_local_search(atis_data, "show flights from washington to san francisco", AbstractString[])

In [ ]:
greedy_local_search(atis_data, "show cheapest flights")

In [ ]:
greedy_local_search(atis_data, "show cheapest flight from washington to san francisco", AbstractString[])

In [ ]:
greedy_local_search(atis_data, "show cheapest and shortest flights from washington to san francisco", AbstractString[])

In [ ]:
target = lookup_sowe(atis_data,"show cheapest flights from washington to san francisco")
target += lookup_sowe(atis_data,"show shortest flights from washington to san francisco")
target./=1.6
greedy_local_search(atis_data,target)

In [ ]:
`git push` |> run

In [ ]:
using UnicodePlots
using IJulia

for τ in τlog
    nw = zip(τ,atis_data["indexed_words"]) |> collect
    
    freq,name = zip(select!(nw, 1:min(20,length(nw)), by=fw->-fw[1])...) |> collect
    IJulia.display(barplot(name|> collect,freq|> collect))
end


In [ ]:
using DataStructures
using DataStructuresExtended


@fastmath function get_prior_fun(uni_occur, bi_joint, prob_length, end_index)
    n_edges=length(uni_occur)
    bi_marginal = sum(bi_joint,1)
    bi_conditional = bi_joint./bi_marginal
  
    
    @inline function joint(aa::Int64)
        @inbounds ret = bi_marginal[aa]
        ret
    end
    
    @inline function joint(aa::Int64,bb::Int64)
        @inbounds ret = bi_joint[aa, bb]
        ret
    end
    
    joint_cache_stats = Dict([("hits",0), ("misses",0)])
    joint_cache = Dict{Accumulator{Int64,Int64}, Float64}() #TODO Should Use a multiset instead to index
    @inline function joint(xxs...) 
        @assert(length(xxs)>=3)
        xxs_bag = counter(Int64, xxs) 
        if !(haskey(joint_cache,xxs_bag))
            joint_cache_stats["misses"]+=1
            #Full calc
            joint_cache[xxs_bag] = mean(Float64[(joint(aas...)*joint(bbs...)) for (aas,bbs) in  nonempty_subset_splits(xxs)])
            
            
        else
            joint_cache_stats["hits"]+=1
        end
        joint_cache[xxs_bag]
    end
    
    conditional_occurance::Function
    @inbounds function conditional_occurance(ws::Vector{Int64})
        if length(ws) == 0
            uni_occur
        elseif length(ws)==1
            bi_conditional[:,ws[1]]
        else
            Float64[joint(aa,ws...) for aa in 1:n_edges]./joint(ws...)
        end
    end
    
    function prior(ws)
        if  length(ws) > length(prob_length) #If it is longer than the tail of length distro, just force temrination
            force_end_pmf = zeros(n_edges) #This PMF forces the sentence to end, if it is returned
            @inbounds force_end_pmf[end_index]=1.0
            force_end_pmf
        else 
            #Either do not end (P=1-P_end) or end (P=P_end)
            #prob_end = prob_length[length(ws)]   #Chance to end at this length
            prob_end=0.0
            prob_occurance::Vector{Float64} = conditional_occurance(ws)
            
            choices_prob = (1.0-prob_end).*prob_occurance
            #@inbounds choices_prob[end_index]=prob_end
            choices_prob
        end 
    end
    prior,joint_cache_stats
end

function get_prior_fun(data::Dict)
    get_prior_fun(data["unioccur"],data["bioccur"], data["length_prob"], data["word_indexes"][END_MARKER])
end

In [ ]:
atis_prior,atis_prior_cache_stats = get_prior_fun(atis_data)
r = @time atis_prior(Int64[1,2,5,4,5,6,7]) #9.335965 seconds
println(atis_prior_cache_stats)
r

In [ ]:
atis_data["indexed_words"][200:300]

In [ ]:
optimise(atis_data,"what is the shortest flight", 1, 1, 0.1, 10000,20)

In [ ]:
optimise(atis_data,"what is the first flight from washington to washington", 1, 1, 0.1, 10000,20)

In [ ]:
optimise(atis_data,"what are the ground transport options", 1, 1, 0.1, 1000,20)

In [ ]:
optimise(atis_data,"where can i go", 1, 1, 0.1, 1000,20)

In [ ]:
atis_data["word_indexes"][START_MARKER]
    

In [ ]:
`git push""` |> run

In [ ]:
`git commit -m="" -a` |> run