In [1]:
using Iterators
using Pipe
using Compat

macro printval(ee)
    ee_expr = @sprintf "%s" string(ee)
    esc(:(println($ee_expr," = ", $ee)))
end

macro pz(ee)
    ee_expr = @sprintf "%s" string(ee)
    esc(:(println($ee_expr,"\t\t",typeof($ee), "\t", size($ee))))
end

push!(LOAD_PATH, ".")
push!(LOAD_PATH, "../util/")

4-element Array{ByteString,1}:
 "/home/ubuntu/build/julia-master/usr/local/share/julia/site/v0.5"
 "/home/ubuntu/build/julia-master/usr/share/julia/site/v0.5"      
 "."                                                              
 "../util/"                                                       

In [2]:
addprocs(11)

11-element Array{Int64,1}:
  2
  3
  4
  5
  6
  7
  8
  9
 10
 11
 12

In [3]:
@everywhere using Distances

In [4]:

@everywhere atis_data = open("atis_data2.jsz","r") do fh
    deserialize(fh)    
end
test_set = atis_data["test_set"];
atis_data

Dict{ASCIIString,Any} with 7 entries:
  "zeroed_words"  => ASCIIString[]
  "length_prob"   => [0.00273293,0.0141963,0.0332591,0.054354,0.0725396,0.08505…
  "LL"            => 300x1126 Array{Float64,2}:…
  "indexed_words" => AbstractString["the","of","to","and","in","a","for","that"…
  "test_set"      => [SubString{ASCIIString}["what","is","the","cheapest","way"…
  "trigrams"      => Any[("**START1**","**START2**","what"),("**START2**","what…
  "word_indexes"  => Dict{AbstractString,Int64}("carried"=>452,"diabetic"=>1069…

In [5]:
@everywhere function lookup_sowe(data, sent::AbstractString)
    lookup_sowe(data, sent |> split)
end

@everywhere function lookup_sowe{S<:AbstractString}(data, sent::Vector{S})
    sum([data["LL"][:,data["word_indexes"][word]] for word in sent]) 
end

@everywhere function lookup_words(data, path)
    [data["indexed_words"][ii] for ii in path]
end

In [6]:
@everywhere @inline function get_end(LL, ws::Vector{Int64})
    @inbounds sofar = length(ws)>0 ? sum([LL[:,ii] for ii in ws]) : zeros(LL[:,1])
    sofar
end

@everywhere  @fastmath function score_possible_additions(LL, target, ws)
    @inbounds path_ends = LL .+ get_end(LL, ws)
    -sqrt(vec(sum((path_ends .- target).^2,1)))
end   

@everywhere  @inline function fitness(LL, target, path::Vector{Int64})
    #Fitter is smaller
    -euclidean(get_end(LL, path), target)   
end

@everywhere function greedy_addition(LL::Matrix{Float64},
                         target::Vector{Float64},
                         best_word_set::Vector{Int},
                         max_additions = Inf)
    best_score = fitness(LL, target, best_word_set)
    did_improve = true
    cur_additions = 0
    while(did_improve && cur_additions<max_additions)
        cur_additions+=1
        did_improve=false
        addition_scores = score_possible_additions(LL, target, best_word_set)
        addition_score, addition = findmax(addition_scores)
        if addition_score>best_score
            best_score=addition_score
            best_word_set = [best_word_set...,addition]
            #println("+$best_score $(lookup_words(data, best_word_set))")
            did_improve=true
        end
    end
    best_word_set,best_score
end

@everywhere function word_swap_refinement(LL::Matrix{Float64},
                              target::Vector{Float64},
                              best_word_set::Vector{Int}, 
                              max_swaps=1)
    
    initial_word_set = copy(best_word_set)
    best_score = fitness(LL, target, best_word_set)
    
    function update_best!(word_set,score)
        if score>best_score
            best_score=score
            best_word_set = word_set
            #println("*$best_score $(lookup_words(data, best_word_set))")
        end
    end
        
    if max_swaps>0
        for ii in 1:length(initial_word_set)
            word_set = initial_word_set[[1:ii-1; ii+1:end]]
            
            swap2_word_set, swap2_score =  word_swap_refinement(LL, target, word_set, max_swaps-1)
            #The return of swap2 will also cover removing just one
            update_best!(swap2_word_set, swap2_score)
            
            add_word_set, add_score = greedy_addition(LL, target, word_set, 1) #Try adding just one greedily
            update_best!(add_word_set, add_score)
            
        end
    end
    best_word_set,best_score
        
end



@everywhere function greedy_search{S<:AbstractString}(data::Dict, target_sent::Vector{S}, max_swaps=1, rounds=3; log=false)
    target::Vector{Float64} = lookup_sowe(data,target_sent)
    get_words(word_iis) = [data["indexed_words"][ii] for ii in word_iis]
    
    word_iis = Int[]
    score=-Inf
    for round in 1:rounds
        word_iis,score = greedy_addition(data["LL"], target, word_iis)
        log && println("+$score $(get_words(word_iis))")
        if score>=0 break end
        word_iis,score = word_swap_refinement(data["LL"], target, word_iis, max_swaps)
        log && println("-$score $(get_words(word_iis))")
        if score>=0 break end
    end
    get_words(word_iis),score
        
end



In [8]:
target_sent = test_set[14]
println(join(target_sent, " "))
@time sol, score = greedy_search(atis_data, target_sent, log=true)



what are the cheapest flights from denver to pittsburgh that stop in atlanta
+-5.068925465368997 Any["we","to","from","atlanta","are","the","flights","pittsburgh","what","in","denver","cheapest","stop"]
--0.0 Any["to","from","atlanta","are","the","flights","pittsburgh","what","in","denver","cheapest","stop","that"]


(Any["to","from","atlanta","are","the","flights","pittsburgh","what","in","denver","cheapest","stop","that"],-0.0)

  0.277340 seconds (5.89 k allocations: 212.262 MB, 13.88% gc time)


In [9]:
res = pmap([1:length(test_set);], test_set) do ii,target_sent
    sol, score = greedy_search(atis_data, target_sent, 1, 5, log=false)
    (sol, score, ii)
end

13038-element Array{Any,1}:
 (Any["to","to","way","the","denver","is","fly","from","cheapest","oakland","what"],-0.0,1)                                               
 (Any["to","to","i","denver","from","oakland","go","want"],-0.0,2)                                                                        
 (Any["what","to","flight","the","denver","is","from","cheapest","oakland"],-0.0,3)                                                       
 (Any["please","one","way"],-0.0,4)                                                                                                       
 (Any["i","to","m","after","leave","p","five","want"],-0.0,5)                                                                             
 (Any["to","i","to","philadelphia","want","from","dallas","go","sure"],-0.0,6)                                                            
 (Any["will","be","flights","on","lunch","served","which"],-0.0,7)                                                                        

In [11]:
open("atis_res_glove.jsz","w") do fh
    serialize(fh, (Vector{ASCIIString}[sol for (sol, score, ii) in res], test_set)
    )    
end



In [12]:
hard_cases = find(x->x[2]<0, res)
res[hard_cases]

631-element Array{Any,1}:
 (Any["this","the","round","are","fare","of","lowest","trip","which"],-3.6439134957576,85)                                                                                                                                
 (Any["to","san","any","all","city","flights","at","that","san","from","please","boston","tell","the","stops","me"],-3.692491576837481,154)                                                                               
 (Any["on","washington","all","boston","between","me","flights","baltimore","november","please","and","the","tell","fifth","twenty"],-2.9618302472727227,156)                                                             
 (Any["i","you","will","morning","the","what","in","flight","leaves","me","in","arrives","frequently","please","that","the","evening","**START1**","take"],-5.886880734491557,160)                                        
 (Any["on","from","flights","june","arrive","boston","tell","eleven","in","depart","me","**START1*

In [13]:
test_set[hard_cases]

631-element Array{Array{SubString{ASCIIString},1},1}:
 SubString{ASCIIString}["which","of","these","is","the","lowest","round","trip","fare"]                                                                                                  
 SubString{ASCIIString}["please","tell","me","all","the","flights","from","boston","to","san","francisco","that","stops","at","any","city"]                                              
 SubString{ASCIIString}["please","tell","me","all","the","flights","between","boston","and","baltimore","washington","on","november","twenty","third"]                                   
 SubString{ASCIIString}["please","tell","me","what","flight","i","can","take","that","arrives","in","the","morning","and","leaves","in","the","evening"]                                 
 SubString{ASCIIString}["please","tell","me","what","flights","depart","from","baltimore","and","arrive","in","boston","on","tuesday","november","twenty"]                               
 SubString{ASCII

In [14]:
hard_set =  test_set[hard_cases]

hard_res = pmap([1:length(hard_set);], hard_set) do ii,target_sent
    sol, score = greedy_search(atis_data, target_sent, 2,5, log=false)
    (sol, score, ii)
end

261-element Array{Any,1}:
 (Any["that","class","first","flight","has","do"],-0.749290050987327,1)                                                                                                                             
 (Any["if","that","you","there","any","flight","on","meals","tell","were","me","can"],-0.7116376591882416,2)                                                                                        
 (Any["five","type","flight","from","is","francisco","used","aircraft","at","san","leaves","that","boston","m","on","what","twenty","eight"],-0.0,3)                                                
 (Any["morning","leaves","that","please","arrive","flight","me","in","evening","tell","takes","i","what","can","the","the","in"],-0.7290381772504556,4)                                             
 (Any["in","this","flight","arrives","when","denver","not"],-0.7661988352217954,5)                                                                                                        

In [15]:
very_hard_cases = find(x->x[2]<0.0, hard_res)

183-element Array{Int64,1}:
   1
   2
   4
   5
   6
   7
   9
  10
  11
  12
  13
  14
  15
   ⋮
 241
 242
 244
 247
 249
 250
 251
 253
 255
 256
 260
 261

In [17]:
factorial(14)

87178291200

In [16]:
hard_res[very_hard_cases]

183-element Array{Any,1}:
 (Any["that","class","first","flight","has","do"],-0.749290050987327,1)                                                                                                                             
 (Any["if","that","you","there","any","flight","on","meals","tell","were","me","can"],-0.7116376591882416,2)                                                                                        
 (Any["morning","leaves","that","please","arrive","flight","me","in","evening","tell","takes","i","what","can","the","the","in"],-0.7290381772504556,4)                                             
 (Any["in","this","flight","arrives","when","denver","not"],-0.7661988352217954,5)                                                                                                                  
 (Any["one","the","do","forty","meals","kind","flight","six","m","has","what"],-0.749290050987327,6)                                                                                      

In [ ]:


for (ii,target_sent) in enumerate(test_set)
    sol, score = greedy_search(atis_data, target_sent, log=false)
    if score>0
        print("$ii - ")
        println(join(target_sent, " "))
    end
end
    

In [ ]:
enumerate(test_set) |> collect

In [ ]:
# τ = Pheromone
# η = Prior
# α = pheremone weight
# β = prior weight
# ρ = pheremone evaporation

@everywhere @inline function select_index{V<:AbstractVector}(edge_probs::V)
    cutoff = rand()
    total = 0.0
    @assert(length(edge_probs)>0, "No probs given")
    for (ii,prob) in enumerate(edge_probs)
        total+=prob
        if total>=cutoff
            return ii
        end
    end
    
    @assert(total>=cutoff, "total= $total, cutoff=$cutoff, $edge_probs") #Should Never Reach this point
end


@everywhere function evaporate!{M<:AbstractArray}(τ::M, ρ)
    τ.*=(1.0-ρ) #Evaporation
end

    

@everywhere function deposit!{M<:AbstractVector}(τ::M, path, fit)
    #Are You In or Out?  Double Crosser or Devout
    #Order actually means nothing in this problem
    #Cooccurance doesn't really many anything either
    #Cooccurance is a problem for the prior that need 
    #to be conerned with all answers not just this one
    for node in path
        @inbounds τ[node] += fit./length(path)
    end
    τ
end

@everywhere function get_edge_probs(τ,η::Function, α, β)
    τ_scaled = (τ).^α
    function get_prob(state)
        η_scaled = (η(state)).^β
        tot = τ_scaled .* τ_scaled
        tot./sum(tot)
    end
end

@everywhere @inline function select_node(edge_probs::Function, path=[])
    select_index(edge_probs(path))
end


In [ ]:
sort!([-1,-2,32,23,42], by=pf->pf)

In [ ]:
#If you pass in a start index of greater than zero, then atre using a starting index, otherswise not
@everywhere function run_ant(edge_probs, end_prob_dist)
    path = Int[]
    len = select_index(end_prob_dist)
    for _ in 1:len
        push!(path, select_node(edge_probs, path))
    end
    path    
end


function optimise(fit_fun, τ, η, end_prob_dist;  α=1, β=1,ρ=0, n_ants=100, n_gens=10, callback=Union{})
    assert(α>=1.0)
    assert(β>=1.0)
    assert(0.0<=ρ<1.0)
    
    max_fit::Float64 = -Inf;
    fittest_path::Vector{Int} = []
    
    for gen_ii in 1:n_gens

        edge_probs = get_edge_probs(τ,η, α, β)

        path_fits::Vector{Tuple{Vector{Int},Float64}} = map(1:n_ants) do ant_id
            path::Vector{Int} = run_ant(edge_probs, end_prob_dist)
            fit::Float64 = fit_fun(path)
            (path, fit)
        end
        
        ranked_path_fits = select!(path_fits,1:100, by=pf->-pf[2])
        scales = 100:-1:1
        
        evaporate!(τ,ρ)
        for ((path, fit),scale) in zip(ranked_path_fits,scales)
        #for (path, fit) in path_fits
            if fit>max_fit
                max_fit = fit
                fittest_path = path
                
                if fit==Inf #Perfect Fit
                    return fittest_path, max_fit
                end
            end
            deposit!(τ,path, fit)
        end
        
        if callback |> typeof <:Function
            callback(gen_ii, τ,fittest_path,max_fit,path_fits)
        end
        
    end #Next Generation
    
    fittest_path, max_fit, τ
end


function optimise(fit_fun, n_dims::Int64, η::Function, end_prob_dist; kwargs...)
    τ = [rand() for nn in 1:n_dims]
    
    optimise(fit_fun, τ, η, end_prob_dist;kwargs...)
end


In [ ]:
@fastmath function get_prior_fun(uni_occur,bi_occur)
    n_edges=length(uni_occur)
    function prior(ws)
        if length(ws)==0
            uni_occur
        elseif length(ws)==1
            bi_occur[:,ws[1]]
        else
            (uni_occur + sum([bi_occur[:,w] for w in ws]))/(length(ws)+1) #Just average them cos its cheap
        end
    end    
end




In [ ]:
function built_optimise(data::Dict, target_sent::AbstractString, log=False; kwargs...)
    target::Vector{Float64} = lookup_sowe(data,target_sent)
    LL =data["LL"]
    indexed_words=data["indexed_words"]
    @inline function fitness(path)
        #Fitter is larger
        @inbounds path_end = sum([LL[:,ii] for ii in path]) 
        -1.0*euclidean(path_end, target)
    end

    τlog=[]
    if log
        log = (gen_ii, τ,fittest_path,max_fit, path_fits) -> begin
            print("oGen: $gen_ii - fit: $max_fit ")
            print(lookup_words(data, fittest_path))
            #path_lens = [length(pf[1]) for pf in path_fits]
            #print("mean_len = $(mean(path_lens))")
            #print(" max_len = $(maximum(path_lens))")
            println()
            push!(τlog,copy(τ))
            
        end
    end
    
    n_dims = size(LL,2)
    length_dist = data["length_prob"]
    #length_dist = ws->0.5
    prior = get_prior_fun(data["unioccur"], data["bioccur"])
       
    
    
    path, score, τ = optimise(fitness,n_dims, prior, length_dist; callback=log, kwargs...)
    push!(τlog,τ)
    score,lookup_words(data, path), τlog
end

In [ ]:
@time score, words, τlog = built_optimise(atis_data,"show flights from washington to san francisco", true;
α=1, β=1, ρ=0.2, n_ants=10000, n_gens=10);
words

In [ ]:
greedy_local_search(atis_data, "show flights from washington to san francisco", AbstractString[])

In [ ]:
greedy_local_search(atis_data, "show cheapest flights")

In [ ]:
greedy_local_search(atis_data, "show cheapest flight from washington to san francisco", AbstractString[])

In [ ]:
greedy_local_search(atis_data, "show cheapest and shortest flights from washington to san francisco", AbstractString[])

In [ ]:
target = lookup_sowe(atis_data,"show cheapest flights from washington to san francisco")
target += lookup_sowe(atis_data,"show shortest flights from washington to san francisco")
target./=1.6
greedy_local_search(atis_data,target)

In [ ]:
`git push` |> run

In [ ]:
using UnicodePlots
using IJulia

for τ in τlog
    nw = zip(τ,atis_data["indexed_words"]) |> collect
    
    freq,name = zip(select!(nw, 1:min(20,length(nw)), by=fw->-fw[1])...) |> collect
    IJulia.display(barplot(name|> collect,freq|> collect))
end


In [ ]:
using DataStructures
using DataStructuresExtended


@fastmath function get_prior_fun(uni_occur, bi_joint, prob_length, end_index)
    n_edges=length(uni_occur)
    bi_marginal = sum(bi_joint,1)
    bi_conditional = bi_joint./bi_marginal
  
    
    @inline function joint(aa::Int64)
        @inbounds ret = bi_marginal[aa]
        ret
    end
    
    @inline function joint(aa::Int64,bb::Int64)
        @inbounds ret = bi_joint[aa, bb]
        ret
    end
    
    joint_cache_stats = Dict([("hits",0), ("misses",0)])
    joint_cache = Dict{Accumulator{Int64,Int64}, Float64}() #TODO Should Use a multiset instead to index
    @inline function joint(xxs...) 
        @assert(length(xxs)>=3)
        xxs_bag = counter(Int64, xxs) 
        if !(haskey(joint_cache,xxs_bag))
            joint_cache_stats["misses"]+=1
            #Full calc
            joint_cache[xxs_bag] = mean(Float64[(joint(aas...)*joint(bbs...)) for (aas,bbs) in  nonempty_subset_splits(xxs)])
            
            
        else
            joint_cache_stats["hits"]+=1
        end
        joint_cache[xxs_bag]
    end
    
    conditional_occurance::Function
    @inbounds function conditional_occurance(ws::Vector{Int64})
        if length(ws) == 0
            uni_occur
        elseif length(ws)==1
            bi_conditional[:,ws[1]]
        else
            Float64[joint(aa,ws...) for aa in 1:n_edges]./joint(ws...)
        end
    end
    
    function prior(ws)
        if  length(ws) > length(prob_length) #If it is longer than the tail of length distro, just force temrination
            force_end_pmf = zeros(n_edges) #This PMF forces the sentence to end, if it is returned
            @inbounds force_end_pmf[end_index]=1.0
            force_end_pmf
        else 
            #Either do not end (P=1-P_end) or end (P=P_end)
            #prob_end = prob_length[length(ws)]   #Chance to end at this length
            prob_end=0.0
            prob_occurance::Vector{Float64} = conditional_occurance(ws)
            
            choices_prob = (1.0-prob_end).*prob_occurance
            #@inbounds choices_prob[end_index]=prob_end
            choices_prob
        end 
    end
    prior,joint_cache_stats
end

function get_prior_fun(data::Dict)
    get_prior_fun(data["unioccur"],data["bioccur"], data["length_prob"], data["word_indexes"][END_MARKER])
end

In [ ]:
atis_prior,atis_prior_cache_stats = get_prior_fun(atis_data)
r = @time atis_prior(Int64[1,2,5,4,5,6,7]) #9.335965 seconds
println(atis_prior_cache_stats)
r

In [ ]:
atis_data["indexed_words"][200:300]

In [ ]:
optimise(atis_data,"what is the shortest flight", 1, 1, 0.1, 10000,20)

In [ ]:
optimise(atis_data,"what is the first flight from washington to washington", 1, 1, 0.1, 10000,20)

In [ ]:
optimise(atis_data,"what are the ground transport options", 1, 1, 0.1, 1000,20)

In [ ]:
optimise(atis_data,"where can i go", 1, 1, 0.1, 1000,20)

In [ ]:
atis_data["word_indexes"][START_MARKER]
    

In [ ]:
`git push""` |> run

In [ ]:
`git commit -m="" -a` |> run